package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAdminAction;

public interface EcsAdminActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int insert(EcsAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    EcsAdminAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    List<EcsAdminAction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdminAction record);
}