package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAd;

public interface EcsAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int insert(EcsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    EcsAd selectByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    List<EcsAd> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAd record);
}