package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAccountLog;

public interface EcsAccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_account_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_account_log
     *
     * @mbg.generated
     */
    int insert(EcsAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_account_log
     *
     * @mbg.generated
     */
    EcsAccountLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_account_log
     *
     * @mbg.generated
     */
    List<EcsAccountLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_account_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAccountLog record);
}