package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAdPosition;

public interface EcsAdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad_position
     *
     * @mbg.generated
     */
    int insert(EcsAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad_position
     *
     * @mbg.generated
     */
    EcsAdPosition selectByPrimaryKey(Byte positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad_position
     *
     * @mbg.generated
     */
    List<EcsAdPosition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdPosition record);
}