package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAdminLog;

public interface EcsAdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_log
     *
     * @mbg.generated
     */
    int insert(EcsAdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_log
     *
     * @mbg.generated
     */
    EcsAdminLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_log
     *
     * @mbg.generated
     */
    List<EcsAdminLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdminLog record);
}