package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAArticle;

public interface EcsAArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_a_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_a_article
     *
     * @mbg.generated
     */
    int insert(EcsAArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_a_article
     *
     * @mbg.generated
     */
    EcsAArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_a_article
     *
     * @mbg.generated
     */
    List<EcsAArticle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_a_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAArticle record);
}