package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsArticleCat;

public interface EcsArticleCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_article_cat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_article_cat
     *
     * @mbg.generated
     */
    int insert(EcsArticleCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_article_cat
     *
     * @mbg.generated
     */
    EcsArticleCat selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_article_cat
     *
     * @mbg.generated
     */
    List<EcsArticleCat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_article_cat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsArticleCat record);
}