package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsAffiliateLog;

public interface EcsAffiliateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_affiliate_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_affiliate_log
     *
     * @mbg.generated
     */
    int insert(EcsAffiliateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_affiliate_log
     *
     * @mbg.generated
     */
    EcsAffiliateLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_affiliate_log
     *
     * @mbg.generated
     */
    List<EcsAffiliateLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_affiliate_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAffiliateLog record);
}