package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsBonusType;

public interface EcsBonusTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_bonus_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_bonus_type
     *
     * @mbg.generated
     */
    int insert(EcsBonusType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_bonus_type
     *
     * @mbg.generated
     */
    EcsBonusType selectByPrimaryKey(Short typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_bonus_type
     *
     * @mbg.generated
     */
    List<EcsBonusType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_bonus_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsBonusType record);
}