package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsBackReplay;

public interface EcsBackReplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_replay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_replay
     *
     * @mbg.generated
     */
    int insert(EcsBackReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_replay
     *
     * @mbg.generated
     */
    EcsBackReplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_replay
     *
     * @mbg.generated
     */
    List<EcsBackReplay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_replay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsBackReplay record);
}