package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsDistribSort;

public interface EcsDistribSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int insert(EcsDistribSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    EcsDistribSort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    List<EcsDistribSort> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDistribSort record);
}