package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEgoQaAnswer;
import org.lint.Entity.EcsEgoQaAnswerWithBLOBs;

public interface EcsEgoQaAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int insert(EcsEgoQaAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    EcsEgoQaAnswerWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    List<EcsEgoQaAnswer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoQaAnswer record);
}