package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEgoVideo;

public interface EcsEgoVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int insert(EcsEgoVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    EcsEgoVideo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    List<EcsEgoVideo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoVideo record);
}