package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEcsmartAd;

public interface EcsEcsmartAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_ad
     *
     * @mbg.generated
     */
    int insert(EcsEcsmartAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_ad
     *
     * @mbg.generated
     */
    EcsEcsmartAd selectByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_ad
     *
     * @mbg.generated
     */
    List<EcsEcsmartAd> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEcsmartAd record);
}