package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEmail;

public interface EcsEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_email
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_email
     *
     * @mbg.generated
     */
    int insert(EcsEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_email
     *
     * @mbg.generated
     */
    EcsEmail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_email
     *
     * @mbg.generated
     */
    List<EcsEmail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_email
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEmail record);
}