package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEcsmartMenu;

public interface EcsEcsmartMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_menu
     *
     * @mbg.generated
     */
    int insert(EcsEcsmartMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_menu
     *
     * @mbg.generated
     */
    EcsEcsmartMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_menu
     *
     * @mbg.generated
     */
    List<EcsEcsmartMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ecsmart_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEcsmartMenu record);
}