package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsEgoCover;

public interface EcsEgoCoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_cover
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_cover
     *
     * @mbg.generated
     */
    int insert(EcsEgoCover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_cover
     *
     * @mbg.generated
     */
    EcsEgoCover selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_cover
     *
     * @mbg.generated
     */
    List<EcsEgoCover> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_cover
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoCover record);
}