package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsExchangeGoods;

public interface EcsExchangeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_exchange_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_exchange_goods
     *
     * @mbg.generated
     */
    int insert(EcsExchangeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_exchange_goods
     *
     * @mbg.generated
     */
    EcsExchangeGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_exchange_goods
     *
     * @mbg.generated
     */
    List<EcsExchangeGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_exchange_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsExchangeGoods record);
}