package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsGoodsActivity;
import org.lint.Entity.EcsGoodsActivityWithBLOBs;

public interface EcsGoodsActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int insert(EcsGoodsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    EcsGoodsActivityWithBLOBs selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    List<EcsGoodsActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsGoodsActivity record);
}