package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsKeyword;

public interface EcsKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keyword
     *
     * @mbg.generated
     */
    int insert(EcsKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keyword
     *
     * @mbg.generated
     */
    EcsKeyword selectByPrimaryKey(Long wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keyword
     *
     * @mbg.generated
     */
    List<EcsKeyword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsKeyword record);
}