package org.lint.DAO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lint.Entity.EcsLinkGoods;

public interface EcsLinkGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_link_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("goodsId") Integer goodsId, @Param("linkGoodsId") Integer linkGoodsId, @Param("adminId") Byte adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_link_goods
     *
     * @mbg.generated
     */
    int insert(EcsLinkGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_link_goods
     *
     * @mbg.generated
     */
    EcsLinkGoods selectByPrimaryKey(@Param("goodsId") Integer goodsId, @Param("linkGoodsId") Integer linkGoodsId, @Param("adminId") Byte adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_link_goods
     *
     * @mbg.generated
     */
    List<EcsLinkGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_link_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsLinkGoods record);
}