package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsMemberPrice;

public interface EcsMemberPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_member_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_member_price
     *
     * @mbg.generated
     */
    int insert(EcsMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_member_price
     *
     * @mbg.generated
     */
    EcsMemberPrice selectByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_member_price
     *
     * @mbg.generated
     */
    List<EcsMemberPrice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsMemberPrice record);
}