package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsOrderGoods;

public interface EcsOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    int insert(EcsOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    EcsOrderGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    List<EcsOrderGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsOrderGoods record);
}