package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsPack;

public interface EcsPackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_pack
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte packId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_pack
     *
     * @mbg.generated
     */
    int insert(EcsPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_pack
     *
     * @mbg.generated
     */
    EcsPack selectByPrimaryKey(Byte packId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_pack
     *
     * @mbg.generated
     */
    List<EcsPack> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_pack
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsPack record);
}