package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsQuestion;

public interface EcsQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int insert(EcsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    EcsQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    List<EcsQuestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsQuestion record);
}