package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsRole;
import org.lint.Entity.EcsRoleWithBLOBs;

public interface EcsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int insert(EcsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    EcsRoleWithBLOBs selectByPrimaryKey(Short roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    List<EcsRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsRole record);
}