package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsSupplierRebate;

public interface EcsSupplierRebateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rebateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int insert(EcsSupplierRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    EcsSupplierRebate selectByPrimaryKey(Integer rebateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    List<EcsSupplierRebate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierRebate record);
}