package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsShaidanImg;

public interface EcsShaidanImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shaidan_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shaidan_img
     *
     * @mbg.generated
     */
    int insert(EcsShaidanImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shaidan_img
     *
     * @mbg.generated
     */
    EcsShaidanImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shaidan_img
     *
     * @mbg.generated
     */
    List<EcsShaidanImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shaidan_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsShaidanImg record);
}