package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsSupplierAdminAction;

public interface EcsSupplierAdminActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_action
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_action
     *
     * @mbg.generated
     */
    int insert(EcsSupplierAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_action
     *
     * @mbg.generated
     */
    EcsSupplierAdminAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_action
     *
     * @mbg.generated
     */
    List<EcsSupplierAdminAction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierAdminAction record);
}