package org.lint.DAO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lint.Entity.EcsSupplierGoodsCat;

public interface EcsSupplierGoodsCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_goods_cat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("goodsId") Integer goodsId, @Param("catId") Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_goods_cat
     *
     * @mbg.generated
     */
    int insert(EcsSupplierGoodsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_goods_cat
     *
     * @mbg.generated
     */
    EcsSupplierGoodsCat selectByPrimaryKey(@Param("goodsId") Integer goodsId, @Param("catId") Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_goods_cat
     *
     * @mbg.generated
     */
    List<EcsSupplierGoodsCat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_goods_cat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierGoodsCat record);
}