package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsSessions;

public interface EcsSessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_sessions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sesskey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_sessions
     *
     * @mbg.generated
     */
    int insert(EcsSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_sessions
     *
     * @mbg.generated
     */
    EcsSessions selectByPrimaryKey(String sesskey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_sessions
     *
     * @mbg.generated
     */
    List<EcsSessions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_sessions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSessions record);
}