package org.lint.DAO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lint.Entity.EcsSupplierCatRecommend;

public interface EcsSupplierCatRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("catId") Short catId, @Param("recommendType") byte[] recommendType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int insert(EcsSupplierCatRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    EcsSupplierCatRecommend selectByPrimaryKey(@Param("catId") Short catId, @Param("recommendType") byte[] recommendType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    List<EcsSupplierCatRecommend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierCatRecommend record);
}