package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsSupplierCategory;

public interface EcsSupplierCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_category
     *
     * @mbg.generated
     */
    int insert(EcsSupplierCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_category
     *
     * @mbg.generated
     */
    EcsSupplierCategory selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_category
     *
     * @mbg.generated
     */
    List<EcsSupplierCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierCategory record);
}