package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsTakegoods;

public interface EcsTakegoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods
     *
     * @mbg.generated
     */
    int insert(EcsTakegoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods
     *
     * @mbg.generated
     */
    EcsTakegoods selectByPrimaryKey(Integer tgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods
     *
     * @mbg.generated
     */
    List<EcsTakegoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsTakegoods record);
}