package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsTakegoodsOrder;

public interface EcsTakegoodsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_order
     *
     * @mbg.generated
     */
    int insert(EcsTakegoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_order
     *
     * @mbg.generated
     */
    EcsTakegoodsOrder selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_order
     *
     * @mbg.generated
     */
    List<EcsTakegoodsOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsTakegoodsOrder record);
}