package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsTakegoodsTypeGoods;

public interface EcsTakegoodsTypeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int insert(EcsTakegoodsTypeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    EcsTakegoodsTypeGoods selectByPrimaryKey(Integer tgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    List<EcsTakegoodsTypeGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsTakegoodsTypeGoods record);
}