package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsUserRank;

public interface EcsUserRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_rank
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_rank
     *
     * @mbg.generated
     */
    int insert(EcsUserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_rank
     *
     * @mbg.generated
     */
    EcsUserRank selectByPrimaryKey(Byte rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_rank
     *
     * @mbg.generated
     */
    List<EcsUserRank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsUserRank record);
}