package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsUserAddress;

public interface EcsUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_address
     *
     * @mbg.generated
     */
    int insert(EcsUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_address
     *
     * @mbg.generated
     */
    EcsUserAddress selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_address
     *
     * @mbg.generated
     */
    List<EcsUserAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_user_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsUserAddress record);
}