package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsWeixinSignconf;

public interface EcsWeixinSignconfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_signconf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_signconf
     *
     * @mbg.generated
     */
    int insert(EcsWeixinSignconf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_signconf
     *
     * @mbg.generated
     */
    EcsWeixinSignconf selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_signconf
     *
     * @mbg.generated
     */
    List<EcsWeixinSignconf> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_signconf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinSignconf record);
}