package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsWeixinConfig;

public interface EcsWeixinConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_config
     *
     * @mbg.generated
     */
    int insert(EcsWeixinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_config
     *
     * @mbg.generated
     */
    EcsWeixinConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_config
     *
     * @mbg.generated
     */
    List<EcsWeixinConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinConfig record);
}