package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsWeixinAct;

public interface EcsWeixinActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int insert(EcsWeixinAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    EcsWeixinAct selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    List<EcsWeixinAct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinAct record);
}