package org.lint.DAO;

import java.util.List;
import org.lint.Entity.EcsWeixinJflog;

public interface EcsWeixinJflogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_jflog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_jflog
     *
     * @mbg.generated
     */
    int insert(EcsWeixinJflog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_jflog
     *
     * @mbg.generated
     */
    EcsWeixinJflog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_jflog
     *
     * @mbg.generated
     */
    List<EcsWeixinJflog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_jflog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinJflog record);
}