package org.lint.Entity;

public class EcsAgency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_agency.agency_id
     *
     * @mbg.generated
     */
    private Short agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_agency.agency_name
     *
     * @mbg.generated
     */
    private String agencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_agency.agency_desc
     *
     * @mbg.generated
     */
    private String agencyDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_agency.agency_id
     *
     * @return the value of ecs_agency.agency_id
     *
     * @mbg.generated
     */
    public Short getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_agency.agency_id
     *
     * @param agencyId the value for ecs_agency.agency_id
     *
     * @mbg.generated
     */
    public void setAgencyId(Short agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_agency.agency_name
     *
     * @return the value of ecs_agency.agency_name
     *
     * @mbg.generated
     */
    public String getAgencyName() {
        return agencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_agency.agency_name
     *
     * @param agencyName the value for ecs_agency.agency_name
     *
     * @mbg.generated
     */
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName == null ? null : agencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_agency.agency_desc
     *
     * @return the value of ecs_agency.agency_desc
     *
     * @mbg.generated
     */
    public String getAgencyDesc() {
        return agencyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_agency.agency_desc
     *
     * @param agencyDesc the value for ecs_agency.agency_desc
     *
     * @mbg.generated
     */
    public void setAgencyDesc(String agencyDesc) {
        this.agencyDesc = agencyDesc == null ? null : agencyDesc.trim();
    }
}