package org.lint.Entity;

public class EcsAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_id
     *
     * @mbg.generated
     */
    private Short attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.cat_id
     *
     * @mbg.generated
     */
    private Short catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_name
     *
     * @mbg.generated
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_input_type
     *
     * @mbg.generated
     */
    private byte[] attrInputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_type
     *
     * @mbg.generated
     */
    private byte[] attrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_index
     *
     * @mbg.generated
     */
    private byte[] attrIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.sort_order
     *
     * @mbg.generated
     */
    private Byte sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.is_linked
     *
     * @mbg.generated
     */
    private byte[] isLinked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_group
     *
     * @mbg.generated
     */
    private byte[] attrGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.is_attr_gallery
     *
     * @mbg.generated
     */
    private byte[] isAttrGallery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_txm
     *
     * @mbg.generated
     */
    private byte[] attrTxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_attribute.attr_values
     *
     * @mbg.generated
     */
    private String attrValues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_id
     *
     * @return the value of ecs_attribute.attr_id
     *
     * @mbg.generated
     */
    public Short getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_id
     *
     * @param attrId the value for ecs_attribute.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Short attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.cat_id
     *
     * @return the value of ecs_attribute.cat_id
     *
     * @mbg.generated
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.cat_id
     *
     * @param catId the value for ecs_attribute.cat_id
     *
     * @mbg.generated
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_name
     *
     * @return the value of ecs_attribute.attr_name
     *
     * @mbg.generated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_name
     *
     * @param attrName the value for ecs_attribute.attr_name
     *
     * @mbg.generated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_input_type
     *
     * @return the value of ecs_attribute.attr_input_type
     *
     * @mbg.generated
     */
    public byte[] getAttrInputType() {
        return attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_input_type
     *
     * @param attrInputType the value for ecs_attribute.attr_input_type
     *
     * @mbg.generated
     */
    public void setAttrInputType(byte[] attrInputType) {
        this.attrInputType = attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_type
     *
     * @return the value of ecs_attribute.attr_type
     *
     * @mbg.generated
     */
    public byte[] getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_type
     *
     * @param attrType the value for ecs_attribute.attr_type
     *
     * @mbg.generated
     */
    public void setAttrType(byte[] attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_index
     *
     * @return the value of ecs_attribute.attr_index
     *
     * @mbg.generated
     */
    public byte[] getAttrIndex() {
        return attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_index
     *
     * @param attrIndex the value for ecs_attribute.attr_index
     *
     * @mbg.generated
     */
    public void setAttrIndex(byte[] attrIndex) {
        this.attrIndex = attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.sort_order
     *
     * @return the value of ecs_attribute.sort_order
     *
     * @mbg.generated
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.sort_order
     *
     * @param sortOrder the value for ecs_attribute.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.is_linked
     *
     * @return the value of ecs_attribute.is_linked
     *
     * @mbg.generated
     */
    public byte[] getIsLinked() {
        return isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.is_linked
     *
     * @param isLinked the value for ecs_attribute.is_linked
     *
     * @mbg.generated
     */
    public void setIsLinked(byte[] isLinked) {
        this.isLinked = isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_group
     *
     * @return the value of ecs_attribute.attr_group
     *
     * @mbg.generated
     */
    public byte[] getAttrGroup() {
        return attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_group
     *
     * @param attrGroup the value for ecs_attribute.attr_group
     *
     * @mbg.generated
     */
    public void setAttrGroup(byte[] attrGroup) {
        this.attrGroup = attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.is_attr_gallery
     *
     * @return the value of ecs_attribute.is_attr_gallery
     *
     * @mbg.generated
     */
    public byte[] getIsAttrGallery() {
        return isAttrGallery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.is_attr_gallery
     *
     * @param isAttrGallery the value for ecs_attribute.is_attr_gallery
     *
     * @mbg.generated
     */
    public void setIsAttrGallery(byte[] isAttrGallery) {
        this.isAttrGallery = isAttrGallery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_txm
     *
     * @return the value of ecs_attribute.attr_txm
     *
     * @mbg.generated
     */
    public byte[] getAttrTxm() {
        return attrTxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_txm
     *
     * @param attrTxm the value for ecs_attribute.attr_txm
     *
     * @mbg.generated
     */
    public void setAttrTxm(byte[] attrTxm) {
        this.attrTxm = attrTxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_attribute.attr_values
     *
     * @return the value of ecs_attribute.attr_values
     *
     * @mbg.generated
     */
    public String getAttrValues() {
        return attrValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_attribute.attr_values
     *
     * @param attrValues the value for ecs_attribute.attr_values
     *
     * @mbg.generated
     */
    public void setAttrValues(String attrValues) {
        this.attrValues = attrValues == null ? null : attrValues.trim();
    }
}