package org.lint.Entity;

public class EcsArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.cat_id
     *
     * @mbg.generated
     */
    private Short catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.author_email
     *
     * @mbg.generated
     */
    private String authorEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.article_type
     *
     * @mbg.generated
     */
    private byte[] articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.is_open
     *
     * @mbg.generated
     */
    private byte[] isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.open_type
     *
     * @mbg.generated
     */
    private byte[] openType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_article.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.article_id
     *
     * @return the value of ecs_article.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.article_id
     *
     * @param articleId the value for ecs_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.cat_id
     *
     * @return the value of ecs_article.cat_id
     *
     * @mbg.generated
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.cat_id
     *
     * @param catId the value for ecs_article.cat_id
     *
     * @mbg.generated
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.title
     *
     * @return the value of ecs_article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.title
     *
     * @param title the value for ecs_article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.author
     *
     * @return the value of ecs_article.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.author
     *
     * @param author the value for ecs_article.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.author_email
     *
     * @return the value of ecs_article.author_email
     *
     * @mbg.generated
     */
    public String getAuthorEmail() {
        return authorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.author_email
     *
     * @param authorEmail the value for ecs_article.author_email
     *
     * @mbg.generated
     */
    public void setAuthorEmail(String authorEmail) {
        this.authorEmail = authorEmail == null ? null : authorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.keywords
     *
     * @return the value of ecs_article.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.keywords
     *
     * @param keywords the value for ecs_article.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.article_type
     *
     * @return the value of ecs_article.article_type
     *
     * @mbg.generated
     */
    public byte[] getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.article_type
     *
     * @param articleType the value for ecs_article.article_type
     *
     * @mbg.generated
     */
    public void setArticleType(byte[] articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.is_open
     *
     * @return the value of ecs_article.is_open
     *
     * @mbg.generated
     */
    public byte[] getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.is_open
     *
     * @param isOpen the value for ecs_article.is_open
     *
     * @mbg.generated
     */
    public void setIsOpen(byte[] isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.add_time
     *
     * @return the value of ecs_article.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.add_time
     *
     * @param addTime the value for ecs_article.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.file_url
     *
     * @return the value of ecs_article.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.file_url
     *
     * @param fileUrl the value for ecs_article.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.open_type
     *
     * @return the value of ecs_article.open_type
     *
     * @mbg.generated
     */
    public byte[] getOpenType() {
        return openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.open_type
     *
     * @param openType the value for ecs_article.open_type
     *
     * @mbg.generated
     */
    public void setOpenType(byte[] openType) {
        this.openType = openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.link
     *
     * @return the value of ecs_article.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.link
     *
     * @param link the value for ecs_article.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.description
     *
     * @return the value of ecs_article.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.description
     *
     * @param description the value for ecs_article.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_article.content
     *
     * @return the value of ecs_article.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_article.content
     *
     * @param content the value for ecs_article.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}