package org.lint.Entity;

public class EcsAdsense {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_adsense.from_ad
     *
     * @mbg.generated
     */
    private Short fromAd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_adsense.referer
     *
     * @mbg.generated
     */
    private String referer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_adsense.clicks
     *
     * @mbg.generated
     */
    private Integer clicks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_adsense.from_ad
     *
     * @return the value of ecs_adsense.from_ad
     *
     * @mbg.generated
     */
    public Short getFromAd() {
        return fromAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_adsense.from_ad
     *
     * @param fromAd the value for ecs_adsense.from_ad
     *
     * @mbg.generated
     */
    public void setFromAd(Short fromAd) {
        this.fromAd = fromAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_adsense.referer
     *
     * @return the value of ecs_adsense.referer
     *
     * @mbg.generated
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_adsense.referer
     *
     * @param referer the value for ecs_adsense.referer
     *
     * @mbg.generated
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_adsense.clicks
     *
     * @return the value of ecs_adsense.clicks
     *
     * @mbg.generated
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_adsense.clicks
     *
     * @param clicks the value for ecs_adsense.clicks
     *
     * @mbg.generated
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }
}