package org.lint.Entity;

public class EcsAd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.ad_id
     *
     * @mbg.generated
     */
    private Short adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.position_id
     *
     * @mbg.generated
     */
    private Short positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.media_type
     *
     * @mbg.generated
     */
    private Byte mediaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.ad_name
     *
     * @mbg.generated
     */
    private String adName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.ad_link
     *
     * @mbg.generated
     */
    private String adLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.start_time
     *
     * @mbg.generated
     */
    private Integer startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.end_time
     *
     * @mbg.generated
     */
    private Integer endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.link_man
     *
     * @mbg.generated
     */
    private String linkMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.link_email
     *
     * @mbg.generated
     */
    private String linkEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.link_phone
     *
     * @mbg.generated
     */
    private String linkPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.click_count
     *
     * @mbg.generated
     */
    private Integer clickCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.enabled
     *
     * @mbg.generated
     */
    private Byte enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ad.ad_code
     *
     * @mbg.generated
     */
    private String adCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.ad_id
     *
     * @return the value of ecs_ad.ad_id
     *
     * @mbg.generated
     */
    public Short getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.ad_id
     *
     * @param adId the value for ecs_ad.ad_id
     *
     * @mbg.generated
     */
    public void setAdId(Short adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.position_id
     *
     * @return the value of ecs_ad.position_id
     *
     * @mbg.generated
     */
    public Short getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.position_id
     *
     * @param positionId the value for ecs_ad.position_id
     *
     * @mbg.generated
     */
    public void setPositionId(Short positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.media_type
     *
     * @return the value of ecs_ad.media_type
     *
     * @mbg.generated
     */
    public Byte getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.media_type
     *
     * @param mediaType the value for ecs_ad.media_type
     *
     * @mbg.generated
     */
    public void setMediaType(Byte mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.ad_name
     *
     * @return the value of ecs_ad.ad_name
     *
     * @mbg.generated
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.ad_name
     *
     * @param adName the value for ecs_ad.ad_name
     *
     * @mbg.generated
     */
    public void setAdName(String adName) {
        this.adName = adName == null ? null : adName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.ad_link
     *
     * @return the value of ecs_ad.ad_link
     *
     * @mbg.generated
     */
    public String getAdLink() {
        return adLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.ad_link
     *
     * @param adLink the value for ecs_ad.ad_link
     *
     * @mbg.generated
     */
    public void setAdLink(String adLink) {
        this.adLink = adLink == null ? null : adLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.start_time
     *
     * @return the value of ecs_ad.start_time
     *
     * @mbg.generated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.start_time
     *
     * @param startTime the value for ecs_ad.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.end_time
     *
     * @return the value of ecs_ad.end_time
     *
     * @mbg.generated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.end_time
     *
     * @param endTime the value for ecs_ad.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.link_man
     *
     * @return the value of ecs_ad.link_man
     *
     * @mbg.generated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.link_man
     *
     * @param linkMan the value for ecs_ad.link_man
     *
     * @mbg.generated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.link_email
     *
     * @return the value of ecs_ad.link_email
     *
     * @mbg.generated
     */
    public String getLinkEmail() {
        return linkEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.link_email
     *
     * @param linkEmail the value for ecs_ad.link_email
     *
     * @mbg.generated
     */
    public void setLinkEmail(String linkEmail) {
        this.linkEmail = linkEmail == null ? null : linkEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.link_phone
     *
     * @return the value of ecs_ad.link_phone
     *
     * @mbg.generated
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.link_phone
     *
     * @param linkPhone the value for ecs_ad.link_phone
     *
     * @mbg.generated
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.click_count
     *
     * @return the value of ecs_ad.click_count
     *
     * @mbg.generated
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.click_count
     *
     * @param clickCount the value for ecs_ad.click_count
     *
     * @mbg.generated
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.enabled
     *
     * @return the value of ecs_ad.enabled
     *
     * @mbg.generated
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.enabled
     *
     * @param enabled the value for ecs_ad.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ad.ad_code
     *
     * @return the value of ecs_ad.ad_code
     *
     * @mbg.generated
     */
    public String getAdCode() {
        return adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ad.ad_code
     *
     * @param adCode the value for ecs_ad.ad_code
     *
     * @mbg.generated
     */
    public void setAdCode(String adCode) {
        this.adCode = adCode == null ? null : adCode.trim();
    }
}