package org.lint.Entity;

public class EcsBookingGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.rec_id
     *
     * @mbg.generated
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.link_man
     *
     * @mbg.generated
     */
    private String linkMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.goods_desc
     *
     * @mbg.generated
     */
    private String goodsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.goods_number
     *
     * @mbg.generated
     */
    private Short goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.booking_time
     *
     * @mbg.generated
     */
    private Integer bookingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.is_dispose
     *
     * @mbg.generated
     */
    private byte[] isDispose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.dispose_user
     *
     * @mbg.generated
     */
    private String disposeUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.dispose_time
     *
     * @mbg.generated
     */
    private Integer disposeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_booking_goods.dispose_note
     *
     * @mbg.generated
     */
    private String disposeNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.rec_id
     *
     * @return the value of ecs_booking_goods.rec_id
     *
     * @mbg.generated
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.rec_id
     *
     * @param recId the value for ecs_booking_goods.rec_id
     *
     * @mbg.generated
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.user_id
     *
     * @return the value of ecs_booking_goods.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.user_id
     *
     * @param userId the value for ecs_booking_goods.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.email
     *
     * @return the value of ecs_booking_goods.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.email
     *
     * @param email the value for ecs_booking_goods.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.link_man
     *
     * @return the value of ecs_booking_goods.link_man
     *
     * @mbg.generated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.link_man
     *
     * @param linkMan the value for ecs_booking_goods.link_man
     *
     * @mbg.generated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.tel
     *
     * @return the value of ecs_booking_goods.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.tel
     *
     * @param tel the value for ecs_booking_goods.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.goods_id
     *
     * @return the value of ecs_booking_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.goods_id
     *
     * @param goodsId the value for ecs_booking_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.goods_desc
     *
     * @return the value of ecs_booking_goods.goods_desc
     *
     * @mbg.generated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.goods_desc
     *
     * @param goodsDesc the value for ecs_booking_goods.goods_desc
     *
     * @mbg.generated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.goods_number
     *
     * @return the value of ecs_booking_goods.goods_number
     *
     * @mbg.generated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.goods_number
     *
     * @param goodsNumber the value for ecs_booking_goods.goods_number
     *
     * @mbg.generated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.booking_time
     *
     * @return the value of ecs_booking_goods.booking_time
     *
     * @mbg.generated
     */
    public Integer getBookingTime() {
        return bookingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.booking_time
     *
     * @param bookingTime the value for ecs_booking_goods.booking_time
     *
     * @mbg.generated
     */
    public void setBookingTime(Integer bookingTime) {
        this.bookingTime = bookingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.is_dispose
     *
     * @return the value of ecs_booking_goods.is_dispose
     *
     * @mbg.generated
     */
    public byte[] getIsDispose() {
        return isDispose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.is_dispose
     *
     * @param isDispose the value for ecs_booking_goods.is_dispose
     *
     * @mbg.generated
     */
    public void setIsDispose(byte[] isDispose) {
        this.isDispose = isDispose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.dispose_user
     *
     * @return the value of ecs_booking_goods.dispose_user
     *
     * @mbg.generated
     */
    public String getDisposeUser() {
        return disposeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.dispose_user
     *
     * @param disposeUser the value for ecs_booking_goods.dispose_user
     *
     * @mbg.generated
     */
    public void setDisposeUser(String disposeUser) {
        this.disposeUser = disposeUser == null ? null : disposeUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.dispose_time
     *
     * @return the value of ecs_booking_goods.dispose_time
     *
     * @mbg.generated
     */
    public Integer getDisposeTime() {
        return disposeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.dispose_time
     *
     * @param disposeTime the value for ecs_booking_goods.dispose_time
     *
     * @mbg.generated
     */
    public void setDisposeTime(Integer disposeTime) {
        this.disposeTime = disposeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_booking_goods.dispose_note
     *
     * @return the value of ecs_booking_goods.dispose_note
     *
     * @mbg.generated
     */
    public String getDisposeNote() {
        return disposeNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_booking_goods.dispose_note
     *
     * @param disposeNote the value for ecs_booking_goods.dispose_note
     *
     * @mbg.generated
     */
    public void setDisposeNote(String disposeNote) {
        this.disposeNote = disposeNote == null ? null : disposeNote.trim();
    }
}