package org.lint.Entity;

import java.math.BigDecimal;

public class EcsCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.card_id
     *
     * @mbg.generated
     */
    private Byte cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.card_name
     *
     * @mbg.generated
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.card_img
     *
     * @mbg.generated
     */
    private String cardImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.card_fee
     *
     * @mbg.generated
     */
    private BigDecimal cardFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.free_money
     *
     * @mbg.generated
     */
    private BigDecimal freeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_card.card_desc
     *
     * @mbg.generated
     */
    private String cardDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.card_id
     *
     * @return the value of ecs_card.card_id
     *
     * @mbg.generated
     */
    public Byte getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.card_id
     *
     * @param cardId the value for ecs_card.card_id
     *
     * @mbg.generated
     */
    public void setCardId(Byte cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.card_name
     *
     * @return the value of ecs_card.card_name
     *
     * @mbg.generated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.card_name
     *
     * @param cardName the value for ecs_card.card_name
     *
     * @mbg.generated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.card_img
     *
     * @return the value of ecs_card.card_img
     *
     * @mbg.generated
     */
    public String getCardImg() {
        return cardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.card_img
     *
     * @param cardImg the value for ecs_card.card_img
     *
     * @mbg.generated
     */
    public void setCardImg(String cardImg) {
        this.cardImg = cardImg == null ? null : cardImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.card_fee
     *
     * @return the value of ecs_card.card_fee
     *
     * @mbg.generated
     */
    public BigDecimal getCardFee() {
        return cardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.card_fee
     *
     * @param cardFee the value for ecs_card.card_fee
     *
     * @mbg.generated
     */
    public void setCardFee(BigDecimal cardFee) {
        this.cardFee = cardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.free_money
     *
     * @return the value of ecs_card.free_money
     *
     * @mbg.generated
     */
    public BigDecimal getFreeMoney() {
        return freeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.free_money
     *
     * @param freeMoney the value for ecs_card.free_money
     *
     * @mbg.generated
     */
    public void setFreeMoney(BigDecimal freeMoney) {
        this.freeMoney = freeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_card.card_desc
     *
     * @return the value of ecs_card.card_desc
     *
     * @mbg.generated
     */
    public String getCardDesc() {
        return cardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_card.card_desc
     *
     * @param cardDesc the value for ecs_card.card_desc
     *
     * @mbg.generated
     */
    public void setCardDesc(String cardDesc) {
        this.cardDesc = cardDesc == null ? null : cardDesc.trim();
    }
}