package org.lint.Entity;

import java.math.BigDecimal;

public class EcsCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.rec_id
     *
     * @mbg.generated
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.session_id
     *
     * @mbg.generated
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.split_money
     *
     * @mbg.generated
     */
    private BigDecimal splitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_number
     *
     * @mbg.generated
     */
    private Short goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.is_real
     *
     * @mbg.generated
     */
    private byte[] isReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.extension_code
     *
     * @mbg.generated
     */
    private String extensionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.rec_type
     *
     * @mbg.generated
     */
    private byte[] recType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.is_gift
     *
     * @mbg.generated
     */
    private Short isGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.is_shipping
     *
     * @mbg.generated
     */
    private byte[] isShipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.can_handsel
     *
     * @mbg.generated
     */
    private Byte canHandsel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_attr_id
     *
     * @mbg.generated
     */
    private String goodsAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.package_attr_id
     *
     * @mbg.generated
     */
    private String packageAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.promote_price
     *
     * @mbg.generated
     */
    private BigDecimal promotePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_cart.goods_attr
     *
     * @mbg.generated
     */
    private String goodsAttr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.rec_id
     *
     * @return the value of ecs_cart.rec_id
     *
     * @mbg.generated
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.rec_id
     *
     * @param recId the value for ecs_cart.rec_id
     *
     * @mbg.generated
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.user_id
     *
     * @return the value of ecs_cart.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.user_id
     *
     * @param userId the value for ecs_cart.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.session_id
     *
     * @return the value of ecs_cart.session_id
     *
     * @mbg.generated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.session_id
     *
     * @param sessionId the value for ecs_cart.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_id
     *
     * @return the value of ecs_cart.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_id
     *
     * @param goodsId the value for ecs_cart.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_sn
     *
     * @return the value of ecs_cart.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_sn
     *
     * @param goodsSn the value for ecs_cart.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.product_id
     *
     * @return the value of ecs_cart.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.product_id
     *
     * @param productId the value for ecs_cart.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_name
     *
     * @return the value of ecs_cart.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_name
     *
     * @param goodsName the value for ecs_cart.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.market_price
     *
     * @return the value of ecs_cart.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.market_price
     *
     * @param marketPrice the value for ecs_cart.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_price
     *
     * @return the value of ecs_cart.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_price
     *
     * @param goodsPrice the value for ecs_cart.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.split_money
     *
     * @return the value of ecs_cart.split_money
     *
     * @mbg.generated
     */
    public BigDecimal getSplitMoney() {
        return splitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.split_money
     *
     * @param splitMoney the value for ecs_cart.split_money
     *
     * @mbg.generated
     */
    public void setSplitMoney(BigDecimal splitMoney) {
        this.splitMoney = splitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_number
     *
     * @return the value of ecs_cart.goods_number
     *
     * @mbg.generated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_number
     *
     * @param goodsNumber the value for ecs_cart.goods_number
     *
     * @mbg.generated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.is_real
     *
     * @return the value of ecs_cart.is_real
     *
     * @mbg.generated
     */
    public byte[] getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.is_real
     *
     * @param isReal the value for ecs_cart.is_real
     *
     * @mbg.generated
     */
    public void setIsReal(byte[] isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.extension_code
     *
     * @return the value of ecs_cart.extension_code
     *
     * @mbg.generated
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.extension_code
     *
     * @param extensionCode the value for ecs_cart.extension_code
     *
     * @mbg.generated
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.parent_id
     *
     * @return the value of ecs_cart.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.parent_id
     *
     * @param parentId the value for ecs_cart.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.rec_type
     *
     * @return the value of ecs_cart.rec_type
     *
     * @mbg.generated
     */
    public byte[] getRecType() {
        return recType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.rec_type
     *
     * @param recType the value for ecs_cart.rec_type
     *
     * @mbg.generated
     */
    public void setRecType(byte[] recType) {
        this.recType = recType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.is_gift
     *
     * @return the value of ecs_cart.is_gift
     *
     * @mbg.generated
     */
    public Short getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.is_gift
     *
     * @param isGift the value for ecs_cart.is_gift
     *
     * @mbg.generated
     */
    public void setIsGift(Short isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.is_shipping
     *
     * @return the value of ecs_cart.is_shipping
     *
     * @mbg.generated
     */
    public byte[] getIsShipping() {
        return isShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.is_shipping
     *
     * @param isShipping the value for ecs_cart.is_shipping
     *
     * @mbg.generated
     */
    public void setIsShipping(byte[] isShipping) {
        this.isShipping = isShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.can_handsel
     *
     * @return the value of ecs_cart.can_handsel
     *
     * @mbg.generated
     */
    public Byte getCanHandsel() {
        return canHandsel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.can_handsel
     *
     * @param canHandsel the value for ecs_cart.can_handsel
     *
     * @mbg.generated
     */
    public void setCanHandsel(Byte canHandsel) {
        this.canHandsel = canHandsel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_attr_id
     *
     * @return the value of ecs_cart.goods_attr_id
     *
     * @mbg.generated
     */
    public String getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_attr_id
     *
     * @param goodsAttrId the value for ecs_cart.goods_attr_id
     *
     * @mbg.generated
     */
    public void setGoodsAttrId(String goodsAttrId) {
        this.goodsAttrId = goodsAttrId == null ? null : goodsAttrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.add_time
     *
     * @return the value of ecs_cart.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.add_time
     *
     * @param addTime the value for ecs_cart.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.package_attr_id
     *
     * @return the value of ecs_cart.package_attr_id
     *
     * @mbg.generated
     */
    public String getPackageAttrId() {
        return packageAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.package_attr_id
     *
     * @param packageAttrId the value for ecs_cart.package_attr_id
     *
     * @mbg.generated
     */
    public void setPackageAttrId(String packageAttrId) {
        this.packageAttrId = packageAttrId == null ? null : packageAttrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.cost_price
     *
     * @return the value of ecs_cart.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.cost_price
     *
     * @param costPrice the value for ecs_cart.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.promote_price
     *
     * @return the value of ecs_cart.promote_price
     *
     * @mbg.generated
     */
    public BigDecimal getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.promote_price
     *
     * @param promotePrice the value for ecs_cart.promote_price
     *
     * @mbg.generated
     */
    public void setPromotePrice(BigDecimal promotePrice) {
        this.promotePrice = promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_cart.goods_attr
     *
     * @return the value of ecs_cart.goods_attr
     *
     * @mbg.generated
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_cart.goods_attr
     *
     * @param goodsAttr the value for ecs_cart.goods_attr
     *
     * @mbg.generated
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr == null ? null : goodsAttr.trim();
    }
}