package org.lint.Entity;

public class EcsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_id
     *
     * @mbg.generated
     */
    private Short catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_name
     *
     * @mbg.generated
     */
    private String catName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_desc
     *
     * @mbg.generated
     */
    private String catDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.parent_id
     *
     * @mbg.generated
     */
    private Short parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.sort_order
     *
     * @mbg.generated
     */
    private byte[] sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.template_file
     *
     * @mbg.generated
     */
    private String templateFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.measure_unit
     *
     * @mbg.generated
     */
    private String measureUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.show_in_nav
     *
     * @mbg.generated
     */
    private byte[] showInNav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.is_show
     *
     * @mbg.generated
     */
    private byte[] isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.grade
     *
     * @mbg.generated
     */
    private Byte grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.filter_attr
     *
     * @mbg.generated
     */
    private String filterAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.category_index
     *
     * @mbg.generated
     */
    private byte[] categoryIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.category_index_dwt
     *
     * @mbg.generated
     */
    private byte[] categoryIndexDwt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.index_dwt_file
     *
     * @mbg.generated
     */
    private String indexDwtFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.show_in_index
     *
     * @mbg.generated
     */
    private byte[] showInIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_index_rightad
     *
     * @mbg.generated
     */
    private String catIndexRightad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_adimg_1
     *
     * @mbg.generated
     */
    private String catAdimg1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_adurl_1
     *
     * @mbg.generated
     */
    private String catAdurl1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_adimg_2
     *
     * @mbg.generated
     */
    private String catAdimg2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_adurl_2
     *
     * @mbg.generated
     */
    private String catAdurl2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.cat_nameimg
     *
     * @mbg.generated
     */
    private String catNameimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.brand_qq
     *
     * @mbg.generated
     */
    private String brandQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.attr_wwwecshop68com
     *
     * @mbg.generated
     */
    private String attrWwwecshop68com;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.path_name
     *
     * @mbg.generated
     */
    private String pathName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.is_virtual
     *
     * @mbg.generated
     */
    private Integer isVirtual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_category.type_img
     *
     * @mbg.generated
     */
    private String typeImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_id
     *
     * @return the value of ecs_category.cat_id
     *
     * @mbg.generated
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_id
     *
     * @param catId the value for ecs_category.cat_id
     *
     * @mbg.generated
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_name
     *
     * @return the value of ecs_category.cat_name
     *
     * @mbg.generated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_name
     *
     * @param catName the value for ecs_category.cat_name
     *
     * @mbg.generated
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.keywords
     *
     * @return the value of ecs_category.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.keywords
     *
     * @param keywords the value for ecs_category.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_desc
     *
     * @return the value of ecs_category.cat_desc
     *
     * @mbg.generated
     */
    public String getCatDesc() {
        return catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_desc
     *
     * @param catDesc the value for ecs_category.cat_desc
     *
     * @mbg.generated
     */
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc == null ? null : catDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.parent_id
     *
     * @return the value of ecs_category.parent_id
     *
     * @mbg.generated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.parent_id
     *
     * @param parentId the value for ecs_category.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.sort_order
     *
     * @return the value of ecs_category.sort_order
     *
     * @mbg.generated
     */
    public byte[] getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.sort_order
     *
     * @param sortOrder the value for ecs_category.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(byte[] sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.template_file
     *
     * @return the value of ecs_category.template_file
     *
     * @mbg.generated
     */
    public String getTemplateFile() {
        return templateFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.template_file
     *
     * @param templateFile the value for ecs_category.template_file
     *
     * @mbg.generated
     */
    public void setTemplateFile(String templateFile) {
        this.templateFile = templateFile == null ? null : templateFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.measure_unit
     *
     * @return the value of ecs_category.measure_unit
     *
     * @mbg.generated
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.measure_unit
     *
     * @param measureUnit the value for ecs_category.measure_unit
     *
     * @mbg.generated
     */
    public void setMeasureUnit(String measureUnit) {
        this.measureUnit = measureUnit == null ? null : measureUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.show_in_nav
     *
     * @return the value of ecs_category.show_in_nav
     *
     * @mbg.generated
     */
    public byte[] getShowInNav() {
        return showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.show_in_nav
     *
     * @param showInNav the value for ecs_category.show_in_nav
     *
     * @mbg.generated
     */
    public void setShowInNav(byte[] showInNav) {
        this.showInNav = showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.style
     *
     * @return the value of ecs_category.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.style
     *
     * @param style the value for ecs_category.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.is_show
     *
     * @return the value of ecs_category.is_show
     *
     * @mbg.generated
     */
    public byte[] getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.is_show
     *
     * @param isShow the value for ecs_category.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(byte[] isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.grade
     *
     * @return the value of ecs_category.grade
     *
     * @mbg.generated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.grade
     *
     * @param grade the value for ecs_category.grade
     *
     * @mbg.generated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.filter_attr
     *
     * @return the value of ecs_category.filter_attr
     *
     * @mbg.generated
     */
    public String getFilterAttr() {
        return filterAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.filter_attr
     *
     * @param filterAttr the value for ecs_category.filter_attr
     *
     * @mbg.generated
     */
    public void setFilterAttr(String filterAttr) {
        this.filterAttr = filterAttr == null ? null : filterAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.category_index
     *
     * @return the value of ecs_category.category_index
     *
     * @mbg.generated
     */
    public byte[] getCategoryIndex() {
        return categoryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.category_index
     *
     * @param categoryIndex the value for ecs_category.category_index
     *
     * @mbg.generated
     */
    public void setCategoryIndex(byte[] categoryIndex) {
        this.categoryIndex = categoryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.category_index_dwt
     *
     * @return the value of ecs_category.category_index_dwt
     *
     * @mbg.generated
     */
    public byte[] getCategoryIndexDwt() {
        return categoryIndexDwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.category_index_dwt
     *
     * @param categoryIndexDwt the value for ecs_category.category_index_dwt
     *
     * @mbg.generated
     */
    public void setCategoryIndexDwt(byte[] categoryIndexDwt) {
        this.categoryIndexDwt = categoryIndexDwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.index_dwt_file
     *
     * @return the value of ecs_category.index_dwt_file
     *
     * @mbg.generated
     */
    public String getIndexDwtFile() {
        return indexDwtFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.index_dwt_file
     *
     * @param indexDwtFile the value for ecs_category.index_dwt_file
     *
     * @mbg.generated
     */
    public void setIndexDwtFile(String indexDwtFile) {
        this.indexDwtFile = indexDwtFile == null ? null : indexDwtFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.show_in_index
     *
     * @return the value of ecs_category.show_in_index
     *
     * @mbg.generated
     */
    public byte[] getShowInIndex() {
        return showInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.show_in_index
     *
     * @param showInIndex the value for ecs_category.show_in_index
     *
     * @mbg.generated
     */
    public void setShowInIndex(byte[] showInIndex) {
        this.showInIndex = showInIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_index_rightad
     *
     * @return the value of ecs_category.cat_index_rightad
     *
     * @mbg.generated
     */
    public String getCatIndexRightad() {
        return catIndexRightad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_index_rightad
     *
     * @param catIndexRightad the value for ecs_category.cat_index_rightad
     *
     * @mbg.generated
     */
    public void setCatIndexRightad(String catIndexRightad) {
        this.catIndexRightad = catIndexRightad == null ? null : catIndexRightad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_adimg_1
     *
     * @return the value of ecs_category.cat_adimg_1
     *
     * @mbg.generated
     */
    public String getCatAdimg1() {
        return catAdimg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_adimg_1
     *
     * @param catAdimg1 the value for ecs_category.cat_adimg_1
     *
     * @mbg.generated
     */
    public void setCatAdimg1(String catAdimg1) {
        this.catAdimg1 = catAdimg1 == null ? null : catAdimg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_adurl_1
     *
     * @return the value of ecs_category.cat_adurl_1
     *
     * @mbg.generated
     */
    public String getCatAdurl1() {
        return catAdurl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_adurl_1
     *
     * @param catAdurl1 the value for ecs_category.cat_adurl_1
     *
     * @mbg.generated
     */
    public void setCatAdurl1(String catAdurl1) {
        this.catAdurl1 = catAdurl1 == null ? null : catAdurl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_adimg_2
     *
     * @return the value of ecs_category.cat_adimg_2
     *
     * @mbg.generated
     */
    public String getCatAdimg2() {
        return catAdimg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_adimg_2
     *
     * @param catAdimg2 the value for ecs_category.cat_adimg_2
     *
     * @mbg.generated
     */
    public void setCatAdimg2(String catAdimg2) {
        this.catAdimg2 = catAdimg2 == null ? null : catAdimg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_adurl_2
     *
     * @return the value of ecs_category.cat_adurl_2
     *
     * @mbg.generated
     */
    public String getCatAdurl2() {
        return catAdurl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_adurl_2
     *
     * @param catAdurl2 the value for ecs_category.cat_adurl_2
     *
     * @mbg.generated
     */
    public void setCatAdurl2(String catAdurl2) {
        this.catAdurl2 = catAdurl2 == null ? null : catAdurl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.cat_nameimg
     *
     * @return the value of ecs_category.cat_nameimg
     *
     * @mbg.generated
     */
    public String getCatNameimg() {
        return catNameimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.cat_nameimg
     *
     * @param catNameimg the value for ecs_category.cat_nameimg
     *
     * @mbg.generated
     */
    public void setCatNameimg(String catNameimg) {
        this.catNameimg = catNameimg == null ? null : catNameimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.brand_qq
     *
     * @return the value of ecs_category.brand_qq
     *
     * @mbg.generated
     */
    public String getBrandQq() {
        return brandQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.brand_qq
     *
     * @param brandQq the value for ecs_category.brand_qq
     *
     * @mbg.generated
     */
    public void setBrandQq(String brandQq) {
        this.brandQq = brandQq == null ? null : brandQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.attr_wwwecshop68com
     *
     * @return the value of ecs_category.attr_wwwecshop68com
     *
     * @mbg.generated
     */
    public String getAttrWwwecshop68com() {
        return attrWwwecshop68com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.attr_wwwecshop68com
     *
     * @param attrWwwecshop68com the value for ecs_category.attr_wwwecshop68com
     *
     * @mbg.generated
     */
    public void setAttrWwwecshop68com(String attrWwwecshop68com) {
        this.attrWwwecshop68com = attrWwwecshop68com == null ? null : attrWwwecshop68com.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.path_name
     *
     * @return the value of ecs_category.path_name
     *
     * @mbg.generated
     */
    public String getPathName() {
        return pathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.path_name
     *
     * @param pathName the value for ecs_category.path_name
     *
     * @mbg.generated
     */
    public void setPathName(String pathName) {
        this.pathName = pathName == null ? null : pathName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.is_virtual
     *
     * @return the value of ecs_category.is_virtual
     *
     * @mbg.generated
     */
    public Integer getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.is_virtual
     *
     * @param isVirtual the value for ecs_category.is_virtual
     *
     * @mbg.generated
     */
    public void setIsVirtual(Integer isVirtual) {
        this.isVirtual = isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_category.type_img
     *
     * @return the value of ecs_category.type_img
     *
     * @mbg.generated
     */
    public String getTypeImg() {
        return typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_category.type_img
     *
     * @param typeImg the value for ecs_category.type_img
     *
     * @mbg.generated
     */
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg == null ? null : typeImg.trim();
    }
}