package org.lint.Entity;

public class EcsEgoTerm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.cover_id
     *
     * @mbg.generated
     */
    private String coverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.up_id
     *
     * @mbg.generated
     */
    private Long upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.lft
     *
     * @mbg.generated
     */
    private Integer lft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.rgt
     *
     * @mbg.generated
     */
    private Integer rgt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ego_term.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.id
     *
     * @return the value of ecs_ego_term.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.id
     *
     * @param id the value for ecs_ego_term.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.name
     *
     * @return the value of ecs_ego_term.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.name
     *
     * @param name the value for ecs_ego_term.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.cover_id
     *
     * @return the value of ecs_ego_term.cover_id
     *
     * @mbg.generated
     */
    public String getCoverId() {
        return coverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.cover_id
     *
     * @param coverId the value for ecs_ego_term.cover_id
     *
     * @mbg.generated
     */
    public void setCoverId(String coverId) {
        this.coverId = coverId == null ? null : coverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.up_id
     *
     * @return the value of ecs_ego_term.up_id
     *
     * @mbg.generated
     */
    public Long getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.up_id
     *
     * @param upId the value for ecs_ego_term.up_id
     *
     * @mbg.generated
     */
    public void setUpId(Long upId) {
        this.upId = upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.lft
     *
     * @return the value of ecs_ego_term.lft
     *
     * @mbg.generated
     */
    public Integer getLft() {
        return lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.lft
     *
     * @param lft the value for ecs_ego_term.lft
     *
     * @mbg.generated
     */
    public void setLft(Integer lft) {
        this.lft = lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.rgt
     *
     * @return the value of ecs_ego_term.rgt
     *
     * @mbg.generated
     */
    public Integer getRgt() {
        return rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.rgt
     *
     * @param rgt the value for ecs_ego_term.rgt
     *
     * @mbg.generated
     */
    public void setRgt(Integer rgt) {
        this.rgt = rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.status
     *
     * @return the value of ecs_ego_term.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.status
     *
     * @param status the value for ecs_ego_term.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ego_term.description
     *
     * @return the value of ecs_ego_term.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ego_term.description
     *
     * @param description the value for ecs_ego_term.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}