package org.lint.Entity;

public class EcsEcsmartMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ecsmart_menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ecsmart_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ecsmart_menu.menu_img
     *
     * @mbg.generated
     */
    private String menuImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ecsmart_menu.menu_url
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_ecsmart_menu.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ecsmart_menu.id
     *
     * @return the value of ecs_ecsmart_menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ecsmart_menu.id
     *
     * @param id the value for ecs_ecsmart_menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ecsmart_menu.menu_name
     *
     * @return the value of ecs_ecsmart_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ecsmart_menu.menu_name
     *
     * @param menuName the value for ecs_ecsmart_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ecsmart_menu.menu_img
     *
     * @return the value of ecs_ecsmart_menu.menu_img
     *
     * @mbg.generated
     */
    public String getMenuImg() {
        return menuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ecsmart_menu.menu_img
     *
     * @param menuImg the value for ecs_ecsmart_menu.menu_img
     *
     * @mbg.generated
     */
    public void setMenuImg(String menuImg) {
        this.menuImg = menuImg == null ? null : menuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ecsmart_menu.menu_url
     *
     * @return the value of ecs_ecsmart_menu.menu_url
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ecsmart_menu.menu_url
     *
     * @param menuUrl the value for ecs_ecsmart_menu.menu_url
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_ecsmart_menu.sort
     *
     * @return the value of ecs_ecsmart_menu.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_ecsmart_menu.sort
     *
     * @param sort the value for ecs_ecsmart_menu.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}