package org.lint.Entity;

public class EcsFeedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_id
     *
     * @mbg.generated
     */
    private Integer msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_title
     *
     * @mbg.generated
     */
    private String msgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_type
     *
     * @mbg.generated
     */
    private byte[] msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_status
     *
     * @mbg.generated
     */
    private byte[] msgStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_time
     *
     * @mbg.generated
     */
    private Integer msgTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.message_img
     *
     * @mbg.generated
     */
    private String messageImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_area
     *
     * @mbg.generated
     */
    private byte[] msgArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_feedback.msg_content
     *
     * @mbg.generated
     */
    private String msgContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_id
     *
     * @return the value of ecs_feedback.msg_id
     *
     * @mbg.generated
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_id
     *
     * @param msgId the value for ecs_feedback.msg_id
     *
     * @mbg.generated
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.parent_id
     *
     * @return the value of ecs_feedback.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.parent_id
     *
     * @param parentId the value for ecs_feedback.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.user_id
     *
     * @return the value of ecs_feedback.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.user_id
     *
     * @param userId the value for ecs_feedback.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.user_name
     *
     * @return the value of ecs_feedback.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.user_name
     *
     * @param userName the value for ecs_feedback.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.user_email
     *
     * @return the value of ecs_feedback.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.user_email
     *
     * @param userEmail the value for ecs_feedback.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_title
     *
     * @return the value of ecs_feedback.msg_title
     *
     * @mbg.generated
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_title
     *
     * @param msgTitle the value for ecs_feedback.msg_title
     *
     * @mbg.generated
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_type
     *
     * @return the value of ecs_feedback.msg_type
     *
     * @mbg.generated
     */
    public byte[] getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_type
     *
     * @param msgType the value for ecs_feedback.msg_type
     *
     * @mbg.generated
     */
    public void setMsgType(byte[] msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_status
     *
     * @return the value of ecs_feedback.msg_status
     *
     * @mbg.generated
     */
    public byte[] getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_status
     *
     * @param msgStatus the value for ecs_feedback.msg_status
     *
     * @mbg.generated
     */
    public void setMsgStatus(byte[] msgStatus) {
        this.msgStatus = msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_time
     *
     * @return the value of ecs_feedback.msg_time
     *
     * @mbg.generated
     */
    public Integer getMsgTime() {
        return msgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_time
     *
     * @param msgTime the value for ecs_feedback.msg_time
     *
     * @mbg.generated
     */
    public void setMsgTime(Integer msgTime) {
        this.msgTime = msgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.message_img
     *
     * @return the value of ecs_feedback.message_img
     *
     * @mbg.generated
     */
    public String getMessageImg() {
        return messageImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.message_img
     *
     * @param messageImg the value for ecs_feedback.message_img
     *
     * @mbg.generated
     */
    public void setMessageImg(String messageImg) {
        this.messageImg = messageImg == null ? null : messageImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.order_id
     *
     * @return the value of ecs_feedback.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.order_id
     *
     * @param orderId the value for ecs_feedback.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_area
     *
     * @return the value of ecs_feedback.msg_area
     *
     * @mbg.generated
     */
    public byte[] getMsgArea() {
        return msgArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_area
     *
     * @param msgArea the value for ecs_feedback.msg_area
     *
     * @mbg.generated
     */
    public void setMsgArea(byte[] msgArea) {
        this.msgArea = msgArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_feedback.msg_content
     *
     * @return the value of ecs_feedback.msg_content
     *
     * @mbg.generated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_feedback.msg_content
     *
     * @param msgContent the value for ecs_feedback.msg_content
     *
     * @mbg.generated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }
}