package org.lint.Entity;

public class EcsGoodsGallery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.img_id
     *
     * @mbg.generated
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    private String imgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    private String thumbUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.img_original
     *
     * @mbg.generated
     */
    private String imgOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.goods_attr_id
     *
     * @mbg.generated
     */
    private Integer goodsAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.is_attr_image
     *
     * @mbg.generated
     */
    private byte[] isAttrImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_gallery.img_sort
     *
     * @mbg.generated
     */
    private Byte imgSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.img_id
     *
     * @return the value of ecs_goods_gallery.img_id
     *
     * @mbg.generated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.img_id
     *
     * @param imgId the value for ecs_goods_gallery.img_id
     *
     * @mbg.generated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.goods_id
     *
     * @return the value of ecs_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.goods_id
     *
     * @param goodsId the value for ecs_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.img_url
     *
     * @return the value of ecs_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.img_url
     *
     * @param imgUrl the value for ecs_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.img_desc
     *
     * @return the value of ecs_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.img_desc
     *
     * @param imgDesc the value for ecs_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc == null ? null : imgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.thumb_url
     *
     * @return the value of ecs_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    public String getThumbUrl() {
        return thumbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.thumb_url
     *
     * @param thumbUrl the value for ecs_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl == null ? null : thumbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.img_original
     *
     * @return the value of ecs_goods_gallery.img_original
     *
     * @mbg.generated
     */
    public String getImgOriginal() {
        return imgOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.img_original
     *
     * @param imgOriginal the value for ecs_goods_gallery.img_original
     *
     * @mbg.generated
     */
    public void setImgOriginal(String imgOriginal) {
        this.imgOriginal = imgOriginal == null ? null : imgOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.goods_attr_id
     *
     * @return the value of ecs_goods_gallery.goods_attr_id
     *
     * @mbg.generated
     */
    public Integer getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.goods_attr_id
     *
     * @param goodsAttrId the value for ecs_goods_gallery.goods_attr_id
     *
     * @mbg.generated
     */
    public void setGoodsAttrId(Integer goodsAttrId) {
        this.goodsAttrId = goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.is_attr_image
     *
     * @return the value of ecs_goods_gallery.is_attr_image
     *
     * @mbg.generated
     */
    public byte[] getIsAttrImage() {
        return isAttrImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.is_attr_image
     *
     * @param isAttrImage the value for ecs_goods_gallery.is_attr_image
     *
     * @mbg.generated
     */
    public void setIsAttrImage(byte[] isAttrImage) {
        this.isAttrImage = isAttrImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_gallery.img_sort
     *
     * @return the value of ecs_goods_gallery.img_sort
     *
     * @mbg.generated
     */
    public Byte getImgSort() {
        return imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_gallery.img_sort
     *
     * @param imgSort the value for ecs_goods_gallery.img_sort
     *
     * @mbg.generated
     */
    public void setImgSort(Byte imgSort) {
        this.imgSort = imgSort;
    }
}