package org.lint.Entity;

import java.math.BigDecimal;

public class EcsOrderGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.rec_id
     *
     * @mbg.generated
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_number
     *
     * @mbg.generated
     */
    private Short goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.split_money
     *
     * @mbg.generated
     */
    private BigDecimal splitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.send_number
     *
     * @mbg.generated
     */
    private Short sendNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.is_real
     *
     * @mbg.generated
     */
    private byte[] isReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.extension_code
     *
     * @mbg.generated
     */
    private String extensionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.is_gift
     *
     * @mbg.generated
     */
    private Short isGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_attr_id
     *
     * @mbg.generated
     */
    private String goodsAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.comment_state
     *
     * @mbg.generated
     */
    private byte[] commentState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.shaidan_state
     *
     * @mbg.generated
     */
    private byte[] shaidanState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.package_attr_id
     *
     * @mbg.generated
     */
    private String packageAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.is_back
     *
     * @mbg.generated
     */
    private byte[] isBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.promote_price
     *
     * @mbg.generated
     */
    private BigDecimal promotePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_attr
     *
     * @mbg.generated
     */
    private String goodsAttr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.rec_id
     *
     * @return the value of ecs_order_goods.rec_id
     *
     * @mbg.generated
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.rec_id
     *
     * @param recId the value for ecs_order_goods.rec_id
     *
     * @mbg.generated
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.order_id
     *
     * @return the value of ecs_order_goods.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.order_id
     *
     * @param orderId the value for ecs_order_goods.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_id
     *
     * @return the value of ecs_order_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_id
     *
     * @param goodsId the value for ecs_order_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_name
     *
     * @return the value of ecs_order_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_name
     *
     * @param goodsName the value for ecs_order_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_sn
     *
     * @return the value of ecs_order_goods.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_sn
     *
     * @param goodsSn the value for ecs_order_goods.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.product_id
     *
     * @return the value of ecs_order_goods.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.product_id
     *
     * @param productId the value for ecs_order_goods.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_number
     *
     * @return the value of ecs_order_goods.goods_number
     *
     * @mbg.generated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_number
     *
     * @param goodsNumber the value for ecs_order_goods.goods_number
     *
     * @mbg.generated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.market_price
     *
     * @return the value of ecs_order_goods.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.market_price
     *
     * @param marketPrice the value for ecs_order_goods.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_price
     *
     * @return the value of ecs_order_goods.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_price
     *
     * @param goodsPrice the value for ecs_order_goods.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.split_money
     *
     * @return the value of ecs_order_goods.split_money
     *
     * @mbg.generated
     */
    public BigDecimal getSplitMoney() {
        return splitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.split_money
     *
     * @param splitMoney the value for ecs_order_goods.split_money
     *
     * @mbg.generated
     */
    public void setSplitMoney(BigDecimal splitMoney) {
        this.splitMoney = splitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.send_number
     *
     * @return the value of ecs_order_goods.send_number
     *
     * @mbg.generated
     */
    public Short getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.send_number
     *
     * @param sendNumber the value for ecs_order_goods.send_number
     *
     * @mbg.generated
     */
    public void setSendNumber(Short sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.is_real
     *
     * @return the value of ecs_order_goods.is_real
     *
     * @mbg.generated
     */
    public byte[] getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.is_real
     *
     * @param isReal the value for ecs_order_goods.is_real
     *
     * @mbg.generated
     */
    public void setIsReal(byte[] isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.extension_code
     *
     * @return the value of ecs_order_goods.extension_code
     *
     * @mbg.generated
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.extension_code
     *
     * @param extensionCode the value for ecs_order_goods.extension_code
     *
     * @mbg.generated
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.parent_id
     *
     * @return the value of ecs_order_goods.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.parent_id
     *
     * @param parentId the value for ecs_order_goods.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.is_gift
     *
     * @return the value of ecs_order_goods.is_gift
     *
     * @mbg.generated
     */
    public Short getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.is_gift
     *
     * @param isGift the value for ecs_order_goods.is_gift
     *
     * @mbg.generated
     */
    public void setIsGift(Short isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_attr_id
     *
     * @return the value of ecs_order_goods.goods_attr_id
     *
     * @mbg.generated
     */
    public String getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_attr_id
     *
     * @param goodsAttrId the value for ecs_order_goods.goods_attr_id
     *
     * @mbg.generated
     */
    public void setGoodsAttrId(String goodsAttrId) {
        this.goodsAttrId = goodsAttrId == null ? null : goodsAttrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.comment_state
     *
     * @return the value of ecs_order_goods.comment_state
     *
     * @mbg.generated
     */
    public byte[] getCommentState() {
        return commentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.comment_state
     *
     * @param commentState the value for ecs_order_goods.comment_state
     *
     * @mbg.generated
     */
    public void setCommentState(byte[] commentState) {
        this.commentState = commentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.shaidan_state
     *
     * @return the value of ecs_order_goods.shaidan_state
     *
     * @mbg.generated
     */
    public byte[] getShaidanState() {
        return shaidanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.shaidan_state
     *
     * @param shaidanState the value for ecs_order_goods.shaidan_state
     *
     * @mbg.generated
     */
    public void setShaidanState(byte[] shaidanState) {
        this.shaidanState = shaidanState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.package_attr_id
     *
     * @return the value of ecs_order_goods.package_attr_id
     *
     * @mbg.generated
     */
    public String getPackageAttrId() {
        return packageAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.package_attr_id
     *
     * @param packageAttrId the value for ecs_order_goods.package_attr_id
     *
     * @mbg.generated
     */
    public void setPackageAttrId(String packageAttrId) {
        this.packageAttrId = packageAttrId == null ? null : packageAttrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.is_back
     *
     * @return the value of ecs_order_goods.is_back
     *
     * @mbg.generated
     */
    public byte[] getIsBack() {
        return isBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.is_back
     *
     * @param isBack the value for ecs_order_goods.is_back
     *
     * @mbg.generated
     */
    public void setIsBack(byte[] isBack) {
        this.isBack = isBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.cost_price
     *
     * @return the value of ecs_order_goods.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.cost_price
     *
     * @param costPrice the value for ecs_order_goods.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.promote_price
     *
     * @return the value of ecs_order_goods.promote_price
     *
     * @mbg.generated
     */
    public BigDecimal getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.promote_price
     *
     * @param promotePrice the value for ecs_order_goods.promote_price
     *
     * @mbg.generated
     */
    public void setPromotePrice(BigDecimal promotePrice) {
        this.promotePrice = promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_attr
     *
     * @return the value of ecs_order_goods.goods_attr
     *
     * @mbg.generated
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_attr
     *
     * @param goodsAttr the value for ecs_order_goods.goods_attr
     *
     * @mbg.generated
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr == null ? null : goodsAttr.trim();
    }
}