package org.lint.Entity;

public class EcsPackageGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_package_goods.package_id
     *
     * @mbg.generated
     */
    private Integer packageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_package_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_package_goods.admin_id
     *
     * @mbg.generated
     */
    private Byte adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_package_goods.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_package_goods.goods_number
     *
     * @mbg.generated
     */
    private Short goodsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_package_goods.package_id
     *
     * @return the value of ecs_package_goods.package_id
     *
     * @mbg.generated
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_package_goods.package_id
     *
     * @param packageId the value for ecs_package_goods.package_id
     *
     * @mbg.generated
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_package_goods.goods_id
     *
     * @return the value of ecs_package_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_package_goods.goods_id
     *
     * @param goodsId the value for ecs_package_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_package_goods.admin_id
     *
     * @return the value of ecs_package_goods.admin_id
     *
     * @mbg.generated
     */
    public Byte getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_package_goods.admin_id
     *
     * @param adminId the value for ecs_package_goods.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Byte adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_package_goods.product_id
     *
     * @return the value of ecs_package_goods.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_package_goods.product_id
     *
     * @param productId the value for ecs_package_goods.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_package_goods.goods_number
     *
     * @return the value of ecs_package_goods.goods_number
     *
     * @mbg.generated
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_package_goods.goods_number
     *
     * @param goodsNumber the value for ecs_package_goods.goods_number
     *
     * @mbg.generated
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }
}