package org.lint.Entity;

public class EcsShopGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.grade_id
     *
     * @mbg.generated
     */
    private Integer gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.comment_rank
     *
     * @mbg.generated
     */
    private byte[] commentRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.server
     *
     * @mbg.generated
     */
    private byte[] server;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.send
     *
     * @mbg.generated
     */
    private byte[] send;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.shipping
     *
     * @mbg.generated
     */
    private byte[] shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shop_grade.is_comment
     *
     * @mbg.generated
     */
    private byte[] isComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.grade_id
     *
     * @return the value of ecs_shop_grade.grade_id
     *
     * @mbg.generated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.grade_id
     *
     * @param gradeId the value for ecs_shop_grade.grade_id
     *
     * @mbg.generated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.user_id
     *
     * @return the value of ecs_shop_grade.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.user_id
     *
     * @param userId the value for ecs_shop_grade.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.user_name
     *
     * @return the value of ecs_shop_grade.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.user_name
     *
     * @param userName the value for ecs_shop_grade.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.add_time
     *
     * @return the value of ecs_shop_grade.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.add_time
     *
     * @param addTime the value for ecs_shop_grade.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.comment_rank
     *
     * @return the value of ecs_shop_grade.comment_rank
     *
     * @mbg.generated
     */
    public byte[] getCommentRank() {
        return commentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.comment_rank
     *
     * @param commentRank the value for ecs_shop_grade.comment_rank
     *
     * @mbg.generated
     */
    public void setCommentRank(byte[] commentRank) {
        this.commentRank = commentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.server
     *
     * @return the value of ecs_shop_grade.server
     *
     * @mbg.generated
     */
    public byte[] getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.server
     *
     * @param server the value for ecs_shop_grade.server
     *
     * @mbg.generated
     */
    public void setServer(byte[] server) {
        this.server = server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.send
     *
     * @return the value of ecs_shop_grade.send
     *
     * @mbg.generated
     */
    public byte[] getSend() {
        return send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.send
     *
     * @param send the value for ecs_shop_grade.send
     *
     * @mbg.generated
     */
    public void setSend(byte[] send) {
        this.send = send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.shipping
     *
     * @return the value of ecs_shop_grade.shipping
     *
     * @mbg.generated
     */
    public byte[] getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.shipping
     *
     * @param shipping the value for ecs_shop_grade.shipping
     *
     * @mbg.generated
     */
    public void setShipping(byte[] shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.order_id
     *
     * @return the value of ecs_shop_grade.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.order_id
     *
     * @param orderId the value for ecs_shop_grade.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.order_sn
     *
     * @return the value of ecs_shop_grade.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.order_sn
     *
     * @param orderSn the value for ecs_shop_grade.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shop_grade.is_comment
     *
     * @return the value of ecs_shop_grade.is_comment
     *
     * @mbg.generated
     */
    public byte[] getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shop_grade.is_comment
     *
     * @param isComment the value for ecs_shop_grade.is_comment
     *
     * @mbg.generated
     */
    public void setIsComment(byte[] isComment) {
        this.isComment = isComment;
    }
}