package org.lint.Entity;

import java.math.BigDecimal;

public class EcsSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_name
     *
     * @mbg.generated
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.rank_id
     *
     * @mbg.generated
     */
    private Byte rankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.type_id
     *
     * @mbg.generated
     */
    private Byte typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.country
     *
     * @mbg.generated
     */
    private Short country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.province
     *
     * @mbg.generated
     */
    private Short province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.city
     *
     * @mbg.generated
     */
    private Short city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.district
     *
     * @mbg.generated
     */
    private Short district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.guimo
     *
     * @mbg.generated
     */
    private String guimo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.company_type
     *
     * @mbg.generated
     */
    private String companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.zhizhao
     *
     * @mbg.generated
     */
    private String zhizhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_back
     *
     * @mbg.generated
     */
    private String contactBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_shop
     *
     * @mbg.generated
     */
    private String contactShop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_yunying
     *
     * @mbg.generated
     */
    private String contactYunying;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_shouhou
     *
     * @mbg.generated
     */
    private String contactShouhou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_caiwu
     *
     * @mbg.generated
     */
    private String contactCaiwu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contact_jishu
     *
     * @mbg.generated
     */
    private String contactJishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.system_fee
     *
     * @mbg.generated
     */
    private BigDecimal systemFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_bond
     *
     * @mbg.generated
     */
    private BigDecimal supplierBond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_rebate
     *
     * @mbg.generated
     */
    private Byte supplierRebate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_rebate_paytime
     *
     * @mbg.generated
     */
    private byte[] supplierRebatePaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_remark
     *
     * @mbg.generated
     */
    private String supplierRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.status
     *
     * @mbg.generated
     */
    private byte[] status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.applynum
     *
     * @mbg.generated
     */
    private Short applynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contacts_name
     *
     * @mbg.generated
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.contacts_phone
     *
     * @mbg.generated
     */
    private String contactsPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.business_licence_number
     *
     * @mbg.generated
     */
    private String businessLicenceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.organization_code
     *
     * @mbg.generated
     */
    private String organizationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.organization_code_electronic
     *
     * @mbg.generated
     */
    private String organizationCodeElectronic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.general_taxpayer
     *
     * @mbg.generated
     */
    private String generalTaxpayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank_account_name
     *
     * @mbg.generated
     */
    private String bankAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank_account_number
     *
     * @mbg.generated
     */
    private String bankAccountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.settlement_bank_account_name
     *
     * @mbg.generated
     */
    private String settlementBankAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.settlement_bank_account_number
     *
     * @mbg.generated
     */
    private String settlementBankAccountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.settlement_bank_name
     *
     * @mbg.generated
     */
    private String settlementBankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.settlement_bank_code
     *
     * @mbg.generated
     */
    private String settlementBankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.tax_registration_certificate
     *
     * @mbg.generated
     */
    private String taxRegistrationCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.taxpayer_id
     *
     * @mbg.generated
     */
    private String taxpayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.bank_licence_electronic
     *
     * @mbg.generated
     */
    private String bankLicenceElectronic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.tax_registration_certificate_electronic
     *
     * @mbg.generated
     */
    private String taxRegistrationCertificateElectronic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.supplier_money
     *
     * @mbg.generated
     */
    private BigDecimal supplierMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.handheld_idcard
     *
     * @mbg.generated
     */
    private String handheldIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.idcard_front
     *
     * @mbg.generated
     */
    private String idcardFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.idcard_reverse
     *
     * @mbg.generated
     */
    private String idcardReverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.nav_list
     *
     * @mbg.generated
     */
    private String navList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier.business_sphere
     *
     * @mbg.generated
     */
    private String businessSphere;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_id
     *
     * @return the value of ecs_supplier.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_id
     *
     * @param supplierId the value for ecs_supplier.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.user_id
     *
     * @return the value of ecs_supplier.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.user_id
     *
     * @param userId the value for ecs_supplier.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_name
     *
     * @return the value of ecs_supplier.supplier_name
     *
     * @mbg.generated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_name
     *
     * @param supplierName the value for ecs_supplier.supplier_name
     *
     * @mbg.generated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.rank_id
     *
     * @return the value of ecs_supplier.rank_id
     *
     * @mbg.generated
     */
    public Byte getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.rank_id
     *
     * @param rankId the value for ecs_supplier.rank_id
     *
     * @mbg.generated
     */
    public void setRankId(Byte rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.type_id
     *
     * @return the value of ecs_supplier.type_id
     *
     * @mbg.generated
     */
    public Byte getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.type_id
     *
     * @param typeId the value for ecs_supplier.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Byte typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.company_name
     *
     * @return the value of ecs_supplier.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.company_name
     *
     * @param companyName the value for ecs_supplier.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.country
     *
     * @return the value of ecs_supplier.country
     *
     * @mbg.generated
     */
    public Short getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.country
     *
     * @param country the value for ecs_supplier.country
     *
     * @mbg.generated
     */
    public void setCountry(Short country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.province
     *
     * @return the value of ecs_supplier.province
     *
     * @mbg.generated
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.province
     *
     * @param province the value for ecs_supplier.province
     *
     * @mbg.generated
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.city
     *
     * @return the value of ecs_supplier.city
     *
     * @mbg.generated
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.city
     *
     * @param city the value for ecs_supplier.city
     *
     * @mbg.generated
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.district
     *
     * @return the value of ecs_supplier.district
     *
     * @mbg.generated
     */
    public Short getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.district
     *
     * @param district the value for ecs_supplier.district
     *
     * @mbg.generated
     */
    public void setDistrict(Short district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.address
     *
     * @return the value of ecs_supplier.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.address
     *
     * @param address the value for ecs_supplier.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.tel
     *
     * @return the value of ecs_supplier.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.tel
     *
     * @param tel the value for ecs_supplier.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.email
     *
     * @return the value of ecs_supplier.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.email
     *
     * @param email the value for ecs_supplier.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.guimo
     *
     * @return the value of ecs_supplier.guimo
     *
     * @mbg.generated
     */
    public String getGuimo() {
        return guimo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.guimo
     *
     * @param guimo the value for ecs_supplier.guimo
     *
     * @mbg.generated
     */
    public void setGuimo(String guimo) {
        this.guimo = guimo == null ? null : guimo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.company_type
     *
     * @return the value of ecs_supplier.company_type
     *
     * @mbg.generated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.company_type
     *
     * @param companyType the value for ecs_supplier.company_type
     *
     * @mbg.generated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank
     *
     * @return the value of ecs_supplier.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank
     *
     * @param bank the value for ecs_supplier.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.zhizhao
     *
     * @return the value of ecs_supplier.zhizhao
     *
     * @mbg.generated
     */
    public String getZhizhao() {
        return zhizhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.zhizhao
     *
     * @param zhizhao the value for ecs_supplier.zhizhao
     *
     * @mbg.generated
     */
    public void setZhizhao(String zhizhao) {
        this.zhizhao = zhizhao == null ? null : zhizhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact
     *
     * @return the value of ecs_supplier.contact
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact
     *
     * @param contact the value for ecs_supplier.contact
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.id_card
     *
     * @return the value of ecs_supplier.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.id_card
     *
     * @param idCard the value for ecs_supplier.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_back
     *
     * @return the value of ecs_supplier.contact_back
     *
     * @mbg.generated
     */
    public String getContactBack() {
        return contactBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_back
     *
     * @param contactBack the value for ecs_supplier.contact_back
     *
     * @mbg.generated
     */
    public void setContactBack(String contactBack) {
        this.contactBack = contactBack == null ? null : contactBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_shop
     *
     * @return the value of ecs_supplier.contact_shop
     *
     * @mbg.generated
     */
    public String getContactShop() {
        return contactShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_shop
     *
     * @param contactShop the value for ecs_supplier.contact_shop
     *
     * @mbg.generated
     */
    public void setContactShop(String contactShop) {
        this.contactShop = contactShop == null ? null : contactShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_yunying
     *
     * @return the value of ecs_supplier.contact_yunying
     *
     * @mbg.generated
     */
    public String getContactYunying() {
        return contactYunying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_yunying
     *
     * @param contactYunying the value for ecs_supplier.contact_yunying
     *
     * @mbg.generated
     */
    public void setContactYunying(String contactYunying) {
        this.contactYunying = contactYunying == null ? null : contactYunying.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_shouhou
     *
     * @return the value of ecs_supplier.contact_shouhou
     *
     * @mbg.generated
     */
    public String getContactShouhou() {
        return contactShouhou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_shouhou
     *
     * @param contactShouhou the value for ecs_supplier.contact_shouhou
     *
     * @mbg.generated
     */
    public void setContactShouhou(String contactShouhou) {
        this.contactShouhou = contactShouhou == null ? null : contactShouhou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_caiwu
     *
     * @return the value of ecs_supplier.contact_caiwu
     *
     * @mbg.generated
     */
    public String getContactCaiwu() {
        return contactCaiwu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_caiwu
     *
     * @param contactCaiwu the value for ecs_supplier.contact_caiwu
     *
     * @mbg.generated
     */
    public void setContactCaiwu(String contactCaiwu) {
        this.contactCaiwu = contactCaiwu == null ? null : contactCaiwu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contact_jishu
     *
     * @return the value of ecs_supplier.contact_jishu
     *
     * @mbg.generated
     */
    public String getContactJishu() {
        return contactJishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contact_jishu
     *
     * @param contactJishu the value for ecs_supplier.contact_jishu
     *
     * @mbg.generated
     */
    public void setContactJishu(String contactJishu) {
        this.contactJishu = contactJishu == null ? null : contactJishu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.system_fee
     *
     * @return the value of ecs_supplier.system_fee
     *
     * @mbg.generated
     */
    public BigDecimal getSystemFee() {
        return systemFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.system_fee
     *
     * @param systemFee the value for ecs_supplier.system_fee
     *
     * @mbg.generated
     */
    public void setSystemFee(BigDecimal systemFee) {
        this.systemFee = systemFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_bond
     *
     * @return the value of ecs_supplier.supplier_bond
     *
     * @mbg.generated
     */
    public BigDecimal getSupplierBond() {
        return supplierBond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_bond
     *
     * @param supplierBond the value for ecs_supplier.supplier_bond
     *
     * @mbg.generated
     */
    public void setSupplierBond(BigDecimal supplierBond) {
        this.supplierBond = supplierBond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_rebate
     *
     * @return the value of ecs_supplier.supplier_rebate
     *
     * @mbg.generated
     */
    public Byte getSupplierRebate() {
        return supplierRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_rebate
     *
     * @param supplierRebate the value for ecs_supplier.supplier_rebate
     *
     * @mbg.generated
     */
    public void setSupplierRebate(Byte supplierRebate) {
        this.supplierRebate = supplierRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_rebate_paytime
     *
     * @return the value of ecs_supplier.supplier_rebate_paytime
     *
     * @mbg.generated
     */
    public byte[] getSupplierRebatePaytime() {
        return supplierRebatePaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_rebate_paytime
     *
     * @param supplierRebatePaytime the value for ecs_supplier.supplier_rebate_paytime
     *
     * @mbg.generated
     */
    public void setSupplierRebatePaytime(byte[] supplierRebatePaytime) {
        this.supplierRebatePaytime = supplierRebatePaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_remark
     *
     * @return the value of ecs_supplier.supplier_remark
     *
     * @mbg.generated
     */
    public String getSupplierRemark() {
        return supplierRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_remark
     *
     * @param supplierRemark the value for ecs_supplier.supplier_remark
     *
     * @mbg.generated
     */
    public void setSupplierRemark(String supplierRemark) {
        this.supplierRemark = supplierRemark == null ? null : supplierRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.status
     *
     * @return the value of ecs_supplier.status
     *
     * @mbg.generated
     */
    public byte[] getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.status
     *
     * @param status the value for ecs_supplier.status
     *
     * @mbg.generated
     */
    public void setStatus(byte[] status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.add_time
     *
     * @return the value of ecs_supplier.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.add_time
     *
     * @param addTime the value for ecs_supplier.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.applynum
     *
     * @return the value of ecs_supplier.applynum
     *
     * @mbg.generated
     */
    public Short getApplynum() {
        return applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.applynum
     *
     * @param applynum the value for ecs_supplier.applynum
     *
     * @mbg.generated
     */
    public void setApplynum(Short applynum) {
        this.applynum = applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contacts_name
     *
     * @return the value of ecs_supplier.contacts_name
     *
     * @mbg.generated
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contacts_name
     *
     * @param contactsName the value for ecs_supplier.contacts_name
     *
     * @mbg.generated
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.contacts_phone
     *
     * @return the value of ecs_supplier.contacts_phone
     *
     * @mbg.generated
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.contacts_phone
     *
     * @param contactsPhone the value for ecs_supplier.contacts_phone
     *
     * @mbg.generated
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.business_licence_number
     *
     * @return the value of ecs_supplier.business_licence_number
     *
     * @mbg.generated
     */
    public String getBusinessLicenceNumber() {
        return businessLicenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.business_licence_number
     *
     * @param businessLicenceNumber the value for ecs_supplier.business_licence_number
     *
     * @mbg.generated
     */
    public void setBusinessLicenceNumber(String businessLicenceNumber) {
        this.businessLicenceNumber = businessLicenceNumber == null ? null : businessLicenceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.organization_code
     *
     * @return the value of ecs_supplier.organization_code
     *
     * @mbg.generated
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.organization_code
     *
     * @param organizationCode the value for ecs_supplier.organization_code
     *
     * @mbg.generated
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.organization_code_electronic
     *
     * @return the value of ecs_supplier.organization_code_electronic
     *
     * @mbg.generated
     */
    public String getOrganizationCodeElectronic() {
        return organizationCodeElectronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.organization_code_electronic
     *
     * @param organizationCodeElectronic the value for ecs_supplier.organization_code_electronic
     *
     * @mbg.generated
     */
    public void setOrganizationCodeElectronic(String organizationCodeElectronic) {
        this.organizationCodeElectronic = organizationCodeElectronic == null ? null : organizationCodeElectronic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.general_taxpayer
     *
     * @return the value of ecs_supplier.general_taxpayer
     *
     * @mbg.generated
     */
    public String getGeneralTaxpayer() {
        return generalTaxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.general_taxpayer
     *
     * @param generalTaxpayer the value for ecs_supplier.general_taxpayer
     *
     * @mbg.generated
     */
    public void setGeneralTaxpayer(String generalTaxpayer) {
        this.generalTaxpayer = generalTaxpayer == null ? null : generalTaxpayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank_account_name
     *
     * @return the value of ecs_supplier.bank_account_name
     *
     * @mbg.generated
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank_account_name
     *
     * @param bankAccountName the value for ecs_supplier.bank_account_name
     *
     * @mbg.generated
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank_account_number
     *
     * @return the value of ecs_supplier.bank_account_number
     *
     * @mbg.generated
     */
    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank_account_number
     *
     * @param bankAccountNumber the value for ecs_supplier.bank_account_number
     *
     * @mbg.generated
     */
    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber == null ? null : bankAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank_name
     *
     * @return the value of ecs_supplier.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank_name
     *
     * @param bankName the value for ecs_supplier.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank_code
     *
     * @return the value of ecs_supplier.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank_code
     *
     * @param bankCode the value for ecs_supplier.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.settlement_bank_account_name
     *
     * @return the value of ecs_supplier.settlement_bank_account_name
     *
     * @mbg.generated
     */
    public String getSettlementBankAccountName() {
        return settlementBankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.settlement_bank_account_name
     *
     * @param settlementBankAccountName the value for ecs_supplier.settlement_bank_account_name
     *
     * @mbg.generated
     */
    public void setSettlementBankAccountName(String settlementBankAccountName) {
        this.settlementBankAccountName = settlementBankAccountName == null ? null : settlementBankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.settlement_bank_account_number
     *
     * @return the value of ecs_supplier.settlement_bank_account_number
     *
     * @mbg.generated
     */
    public String getSettlementBankAccountNumber() {
        return settlementBankAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.settlement_bank_account_number
     *
     * @param settlementBankAccountNumber the value for ecs_supplier.settlement_bank_account_number
     *
     * @mbg.generated
     */
    public void setSettlementBankAccountNumber(String settlementBankAccountNumber) {
        this.settlementBankAccountNumber = settlementBankAccountNumber == null ? null : settlementBankAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.settlement_bank_name
     *
     * @return the value of ecs_supplier.settlement_bank_name
     *
     * @mbg.generated
     */
    public String getSettlementBankName() {
        return settlementBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.settlement_bank_name
     *
     * @param settlementBankName the value for ecs_supplier.settlement_bank_name
     *
     * @mbg.generated
     */
    public void setSettlementBankName(String settlementBankName) {
        this.settlementBankName = settlementBankName == null ? null : settlementBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.settlement_bank_code
     *
     * @return the value of ecs_supplier.settlement_bank_code
     *
     * @mbg.generated
     */
    public String getSettlementBankCode() {
        return settlementBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.settlement_bank_code
     *
     * @param settlementBankCode the value for ecs_supplier.settlement_bank_code
     *
     * @mbg.generated
     */
    public void setSettlementBankCode(String settlementBankCode) {
        this.settlementBankCode = settlementBankCode == null ? null : settlementBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.tax_registration_certificate
     *
     * @return the value of ecs_supplier.tax_registration_certificate
     *
     * @mbg.generated
     */
    public String getTaxRegistrationCertificate() {
        return taxRegistrationCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.tax_registration_certificate
     *
     * @param taxRegistrationCertificate the value for ecs_supplier.tax_registration_certificate
     *
     * @mbg.generated
     */
    public void setTaxRegistrationCertificate(String taxRegistrationCertificate) {
        this.taxRegistrationCertificate = taxRegistrationCertificate == null ? null : taxRegistrationCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.taxpayer_id
     *
     * @return the value of ecs_supplier.taxpayer_id
     *
     * @mbg.generated
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.taxpayer_id
     *
     * @param taxpayerId the value for ecs_supplier.taxpayer_id
     *
     * @mbg.generated
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId == null ? null : taxpayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.bank_licence_electronic
     *
     * @return the value of ecs_supplier.bank_licence_electronic
     *
     * @mbg.generated
     */
    public String getBankLicenceElectronic() {
        return bankLicenceElectronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.bank_licence_electronic
     *
     * @param bankLicenceElectronic the value for ecs_supplier.bank_licence_electronic
     *
     * @mbg.generated
     */
    public void setBankLicenceElectronic(String bankLicenceElectronic) {
        this.bankLicenceElectronic = bankLicenceElectronic == null ? null : bankLicenceElectronic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.tax_registration_certificate_electronic
     *
     * @return the value of ecs_supplier.tax_registration_certificate_electronic
     *
     * @mbg.generated
     */
    public String getTaxRegistrationCertificateElectronic() {
        return taxRegistrationCertificateElectronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.tax_registration_certificate_electronic
     *
     * @param taxRegistrationCertificateElectronic the value for ecs_supplier.tax_registration_certificate_electronic
     *
     * @mbg.generated
     */
    public void setTaxRegistrationCertificateElectronic(String taxRegistrationCertificateElectronic) {
        this.taxRegistrationCertificateElectronic = taxRegistrationCertificateElectronic == null ? null : taxRegistrationCertificateElectronic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.supplier_money
     *
     * @return the value of ecs_supplier.supplier_money
     *
     * @mbg.generated
     */
    public BigDecimal getSupplierMoney() {
        return supplierMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.supplier_money
     *
     * @param supplierMoney the value for ecs_supplier.supplier_money
     *
     * @mbg.generated
     */
    public void setSupplierMoney(BigDecimal supplierMoney) {
        this.supplierMoney = supplierMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.handheld_idcard
     *
     * @return the value of ecs_supplier.handheld_idcard
     *
     * @mbg.generated
     */
    public String getHandheldIdcard() {
        return handheldIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.handheld_idcard
     *
     * @param handheldIdcard the value for ecs_supplier.handheld_idcard
     *
     * @mbg.generated
     */
    public void setHandheldIdcard(String handheldIdcard) {
        this.handheldIdcard = handheldIdcard == null ? null : handheldIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.idcard_front
     *
     * @return the value of ecs_supplier.idcard_front
     *
     * @mbg.generated
     */
    public String getIdcardFront() {
        return idcardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.idcard_front
     *
     * @param idcardFront the value for ecs_supplier.idcard_front
     *
     * @mbg.generated
     */
    public void setIdcardFront(String idcardFront) {
        this.idcardFront = idcardFront == null ? null : idcardFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.idcard_reverse
     *
     * @return the value of ecs_supplier.idcard_reverse
     *
     * @mbg.generated
     */
    public String getIdcardReverse() {
        return idcardReverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.idcard_reverse
     *
     * @param idcardReverse the value for ecs_supplier.idcard_reverse
     *
     * @mbg.generated
     */
    public void setIdcardReverse(String idcardReverse) {
        this.idcardReverse = idcardReverse == null ? null : idcardReverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.id_card_no
     *
     * @return the value of ecs_supplier.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.id_card_no
     *
     * @param idCardNo the value for ecs_supplier.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.nav_list
     *
     * @return the value of ecs_supplier.nav_list
     *
     * @mbg.generated
     */
    public String getNavList() {
        return navList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.nav_list
     *
     * @param navList the value for ecs_supplier.nav_list
     *
     * @mbg.generated
     */
    public void setNavList(String navList) {
        this.navList = navList == null ? null : navList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier.business_sphere
     *
     * @return the value of ecs_supplier.business_sphere
     *
     * @mbg.generated
     */
    public String getBusinessSphere() {
        return businessSphere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier.business_sphere
     *
     * @param businessSphere the value for ecs_supplier.business_sphere
     *
     * @mbg.generated
     */
    public void setBusinessSphere(String businessSphere) {
        this.businessSphere = businessSphere == null ? null : businessSphere.trim();
    }
}