package org.lint.Entity;

public class EcsSupplierRebateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.logid
     *
     * @mbg.generated
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.rebateid
     *
     * @mbg.generated
     */
    private Integer rebateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.type
     *
     * @mbg.generated
     */
    private byte[] type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.typedec
     *
     * @mbg.generated
     */
    private String typedec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.contents
     *
     * @mbg.generated
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_supplier_rebate_log.addtime
     *
     * @mbg.generated
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.logid
     *
     * @return the value of ecs_supplier_rebate_log.logid
     *
     * @mbg.generated
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.logid
     *
     * @param logid the value for ecs_supplier_rebate_log.logid
     *
     * @mbg.generated
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.rebateid
     *
     * @return the value of ecs_supplier_rebate_log.rebateid
     *
     * @mbg.generated
     */
    public Integer getRebateid() {
        return rebateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.rebateid
     *
     * @param rebateid the value for ecs_supplier_rebate_log.rebateid
     *
     * @mbg.generated
     */
    public void setRebateid(Integer rebateid) {
        this.rebateid = rebateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.username
     *
     * @return the value of ecs_supplier_rebate_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.username
     *
     * @param username the value for ecs_supplier_rebate_log.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.type
     *
     * @return the value of ecs_supplier_rebate_log.type
     *
     * @mbg.generated
     */
    public byte[] getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.type
     *
     * @param type the value for ecs_supplier_rebate_log.type
     *
     * @mbg.generated
     */
    public void setType(byte[] type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.typedec
     *
     * @return the value of ecs_supplier_rebate_log.typedec
     *
     * @mbg.generated
     */
    public String getTypedec() {
        return typedec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.typedec
     *
     * @param typedec the value for ecs_supplier_rebate_log.typedec
     *
     * @mbg.generated
     */
    public void setTypedec(String typedec) {
        this.typedec = typedec == null ? null : typedec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.contents
     *
     * @return the value of ecs_supplier_rebate_log.contents
     *
     * @mbg.generated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.contents
     *
     * @param contents the value for ecs_supplier_rebate_log.contents
     *
     * @mbg.generated
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_supplier_rebate_log.addtime
     *
     * @return the value of ecs_supplier_rebate_log.addtime
     *
     * @mbg.generated
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_supplier_rebate_log.addtime
     *
     * @param addtime the value for ecs_supplier_rebate_log.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}