package org.lint.Entity;

public class EcsShipping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_id
     *
     * @mbg.generated
     */
    private Byte shippingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_code
     *
     * @mbg.generated
     */
    private String shippingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_name
     *
     * @mbg.generated
     */
    private String shippingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_desc
     *
     * @mbg.generated
     */
    private String shippingDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.insure
     *
     * @mbg.generated
     */
    private String insure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.support_cod
     *
     * @mbg.generated
     */
    private byte[] supportCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.enabled
     *
     * @mbg.generated
     */
    private byte[] enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.print_bg
     *
     * @mbg.generated
     */
    private String printBg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.print_model
     *
     * @mbg.generated
     */
    private byte[] printModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_order
     *
     * @mbg.generated
     */
    private Byte shippingOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.support_pickup
     *
     * @mbg.generated
     */
    private byte[] supportPickup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.is_default_show
     *
     * @mbg.generated
     */
    private byte[] isDefaultShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.shipping_print
     *
     * @mbg.generated
     */
    private String shippingPrint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_shipping.config_lable
     *
     * @mbg.generated
     */
    private String configLable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_id
     *
     * @return the value of ecs_shipping.shipping_id
     *
     * @mbg.generated
     */
    public Byte getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_id
     *
     * @param shippingId the value for ecs_shipping.shipping_id
     *
     * @mbg.generated
     */
    public void setShippingId(Byte shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_code
     *
     * @return the value of ecs_shipping.shipping_code
     *
     * @mbg.generated
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_code
     *
     * @param shippingCode the value for ecs_shipping.shipping_code
     *
     * @mbg.generated
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_name
     *
     * @return the value of ecs_shipping.shipping_name
     *
     * @mbg.generated
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_name
     *
     * @param shippingName the value for ecs_shipping.shipping_name
     *
     * @mbg.generated
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_desc
     *
     * @return the value of ecs_shipping.shipping_desc
     *
     * @mbg.generated
     */
    public String getShippingDesc() {
        return shippingDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_desc
     *
     * @param shippingDesc the value for ecs_shipping.shipping_desc
     *
     * @mbg.generated
     */
    public void setShippingDesc(String shippingDesc) {
        this.shippingDesc = shippingDesc == null ? null : shippingDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.insure
     *
     * @return the value of ecs_shipping.insure
     *
     * @mbg.generated
     */
    public String getInsure() {
        return insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.insure
     *
     * @param insure the value for ecs_shipping.insure
     *
     * @mbg.generated
     */
    public void setInsure(String insure) {
        this.insure = insure == null ? null : insure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.support_cod
     *
     * @return the value of ecs_shipping.support_cod
     *
     * @mbg.generated
     */
    public byte[] getSupportCod() {
        return supportCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.support_cod
     *
     * @param supportCod the value for ecs_shipping.support_cod
     *
     * @mbg.generated
     */
    public void setSupportCod(byte[] supportCod) {
        this.supportCod = supportCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.enabled
     *
     * @return the value of ecs_shipping.enabled
     *
     * @mbg.generated
     */
    public byte[] getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.enabled
     *
     * @param enabled the value for ecs_shipping.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(byte[] enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.print_bg
     *
     * @return the value of ecs_shipping.print_bg
     *
     * @mbg.generated
     */
    public String getPrintBg() {
        return printBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.print_bg
     *
     * @param printBg the value for ecs_shipping.print_bg
     *
     * @mbg.generated
     */
    public void setPrintBg(String printBg) {
        this.printBg = printBg == null ? null : printBg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.print_model
     *
     * @return the value of ecs_shipping.print_model
     *
     * @mbg.generated
     */
    public byte[] getPrintModel() {
        return printModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.print_model
     *
     * @param printModel the value for ecs_shipping.print_model
     *
     * @mbg.generated
     */
    public void setPrintModel(byte[] printModel) {
        this.printModel = printModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_order
     *
     * @return the value of ecs_shipping.shipping_order
     *
     * @mbg.generated
     */
    public Byte getShippingOrder() {
        return shippingOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_order
     *
     * @param shippingOrder the value for ecs_shipping.shipping_order
     *
     * @mbg.generated
     */
    public void setShippingOrder(Byte shippingOrder) {
        this.shippingOrder = shippingOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.support_pickup
     *
     * @return the value of ecs_shipping.support_pickup
     *
     * @mbg.generated
     */
    public byte[] getSupportPickup() {
        return supportPickup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.support_pickup
     *
     * @param supportPickup the value for ecs_shipping.support_pickup
     *
     * @mbg.generated
     */
    public void setSupportPickup(byte[] supportPickup) {
        this.supportPickup = supportPickup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.supplier_id
     *
     * @return the value of ecs_shipping.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.supplier_id
     *
     * @param supplierId the value for ecs_shipping.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.is_default_show
     *
     * @return the value of ecs_shipping.is_default_show
     *
     * @mbg.generated
     */
    public byte[] getIsDefaultShow() {
        return isDefaultShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.is_default_show
     *
     * @param isDefaultShow the value for ecs_shipping.is_default_show
     *
     * @mbg.generated
     */
    public void setIsDefaultShow(byte[] isDefaultShow) {
        this.isDefaultShow = isDefaultShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.shipping_print
     *
     * @return the value of ecs_shipping.shipping_print
     *
     * @mbg.generated
     */
    public String getShippingPrint() {
        return shippingPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.shipping_print
     *
     * @param shippingPrint the value for ecs_shipping.shipping_print
     *
     * @mbg.generated
     */
    public void setShippingPrint(String shippingPrint) {
        this.shippingPrint = shippingPrint == null ? null : shippingPrint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_shipping.config_lable
     *
     * @return the value of ecs_shipping.config_lable
     *
     * @mbg.generated
     */
    public String getConfigLable() {
        return configLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_shipping.config_lable
     *
     * @param configLable the value for ecs_shipping.config_lable
     *
     * @mbg.generated
     */
    public void setConfigLable(String configLable) {
        this.configLable = configLable == null ? null : configLable.trim();
    }
}