package org.lint.Entity;

public class EcsTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.topic_id
     *
     * @mbg.generated
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.start_time
     *
     * @mbg.generated
     */
    private Integer startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.end_time
     *
     * @mbg.generated
     */
    private Integer endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.template
     *
     * @mbg.generated
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.topic_img
     *
     * @mbg.generated
     */
    private String topicImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.title_pic
     *
     * @mbg.generated
     */
    private String titlePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.base_style
     *
     * @mbg.generated
     */
    private String baseStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.css
     *
     * @mbg.generated
     */
    private String css;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_topic.htmls
     *
     * @mbg.generated
     */
    private String htmls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.topic_id
     *
     * @return the value of ecs_topic.topic_id
     *
     * @mbg.generated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.topic_id
     *
     * @param topicId the value for ecs_topic.topic_id
     *
     * @mbg.generated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.title
     *
     * @return the value of ecs_topic.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.title
     *
     * @param title the value for ecs_topic.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.start_time
     *
     * @return the value of ecs_topic.start_time
     *
     * @mbg.generated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.start_time
     *
     * @param startTime the value for ecs_topic.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.end_time
     *
     * @return the value of ecs_topic.end_time
     *
     * @mbg.generated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.end_time
     *
     * @param endTime the value for ecs_topic.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.template
     *
     * @return the value of ecs_topic.template
     *
     * @mbg.generated
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.template
     *
     * @param template the value for ecs_topic.template
     *
     * @mbg.generated
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.topic_img
     *
     * @return the value of ecs_topic.topic_img
     *
     * @mbg.generated
     */
    public String getTopicImg() {
        return topicImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.topic_img
     *
     * @param topicImg the value for ecs_topic.topic_img
     *
     * @mbg.generated
     */
    public void setTopicImg(String topicImg) {
        this.topicImg = topicImg == null ? null : topicImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.title_pic
     *
     * @return the value of ecs_topic.title_pic
     *
     * @mbg.generated
     */
    public String getTitlePic() {
        return titlePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.title_pic
     *
     * @param titlePic the value for ecs_topic.title_pic
     *
     * @mbg.generated
     */
    public void setTitlePic(String titlePic) {
        this.titlePic = titlePic == null ? null : titlePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.base_style
     *
     * @return the value of ecs_topic.base_style
     *
     * @mbg.generated
     */
    public String getBaseStyle() {
        return baseStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.base_style
     *
     * @param baseStyle the value for ecs_topic.base_style
     *
     * @mbg.generated
     */
    public void setBaseStyle(String baseStyle) {
        this.baseStyle = baseStyle == null ? null : baseStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.keywords
     *
     * @return the value of ecs_topic.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.keywords
     *
     * @param keywords the value for ecs_topic.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.description
     *
     * @return the value of ecs_topic.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.description
     *
     * @param description the value for ecs_topic.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.intro
     *
     * @return the value of ecs_topic.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.intro
     *
     * @param intro the value for ecs_topic.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.data
     *
     * @return the value of ecs_topic.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.data
     *
     * @param data the value for ecs_topic.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.css
     *
     * @return the value of ecs_topic.css
     *
     * @mbg.generated
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.css
     *
     * @param css the value for ecs_topic.css
     *
     * @mbg.generated
     */
    public void setCss(String css) {
        this.css = css == null ? null : css.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_topic.htmls
     *
     * @return the value of ecs_topic.htmls
     *
     * @mbg.generated
     */
    public String getHtmls() {
        return htmls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_topic.htmls
     *
     * @param htmls the value for ecs_topic.htmls
     *
     * @mbg.generated
     */
    public void setHtmls(String htmls) {
        this.htmls = htmls == null ? null : htmls.trim();
    }
}