package org.lint.Entity;

public class EcsUserBonus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.bonus_id
     *
     * @mbg.generated
     */
    private Integer bonusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.bonus_type_id
     *
     * @mbg.generated
     */
    private Byte bonusTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.bonus_sn
     *
     * @mbg.generated
     */
    private Long bonusSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.used_time
     *
     * @mbg.generated
     */
    private Integer usedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.emailed
     *
     * @mbg.generated
     */
    private Byte emailed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_user_bonus.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.bonus_id
     *
     * @return the value of ecs_user_bonus.bonus_id
     *
     * @mbg.generated
     */
    public Integer getBonusId() {
        return bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.bonus_id
     *
     * @param bonusId the value for ecs_user_bonus.bonus_id
     *
     * @mbg.generated
     */
    public void setBonusId(Integer bonusId) {
        this.bonusId = bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.bonus_type_id
     *
     * @return the value of ecs_user_bonus.bonus_type_id
     *
     * @mbg.generated
     */
    public Byte getBonusTypeId() {
        return bonusTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.bonus_type_id
     *
     * @param bonusTypeId the value for ecs_user_bonus.bonus_type_id
     *
     * @mbg.generated
     */
    public void setBonusTypeId(Byte bonusTypeId) {
        this.bonusTypeId = bonusTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.bonus_sn
     *
     * @return the value of ecs_user_bonus.bonus_sn
     *
     * @mbg.generated
     */
    public Long getBonusSn() {
        return bonusSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.bonus_sn
     *
     * @param bonusSn the value for ecs_user_bonus.bonus_sn
     *
     * @mbg.generated
     */
    public void setBonusSn(Long bonusSn) {
        this.bonusSn = bonusSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.user_id
     *
     * @return the value of ecs_user_bonus.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.user_id
     *
     * @param userId the value for ecs_user_bonus.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.used_time
     *
     * @return the value of ecs_user_bonus.used_time
     *
     * @mbg.generated
     */
    public Integer getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.used_time
     *
     * @param usedTime the value for ecs_user_bonus.used_time
     *
     * @mbg.generated
     */
    public void setUsedTime(Integer usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.order_id
     *
     * @return the value of ecs_user_bonus.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.order_id
     *
     * @param orderId the value for ecs_user_bonus.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.emailed
     *
     * @return the value of ecs_user_bonus.emailed
     *
     * @mbg.generated
     */
    public Byte getEmailed() {
        return emailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.emailed
     *
     * @param emailed the value for ecs_user_bonus.emailed
     *
     * @mbg.generated
     */
    public void setEmailed(Byte emailed) {
        this.emailed = emailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_user_bonus.supplier_id
     *
     * @return the value of ecs_user_bonus.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_user_bonus.supplier_id
     *
     * @param supplierId the value for ecs_user_bonus.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
}