package org.lint.Entity;

public class EcsVirtualGoodsDistrict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.district_id
     *
     * @mbg.generated
     */
    private Short districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.region_id
     *
     * @mbg.generated
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.district_name
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.province
     *
     * @mbg.generated
     */
    private Short province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.city
     *
     * @mbg.generated
     */
    private Short city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.county
     *
     * @mbg.generated
     */
    private Short county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_goods_district.is_show
     *
     * @mbg.generated
     */
    private Short isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.district_id
     *
     * @return the value of ecs_virtual_goods_district.district_id
     *
     * @mbg.generated
     */
    public Short getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.district_id
     *
     * @param districtId the value for ecs_virtual_goods_district.district_id
     *
     * @mbg.generated
     */
    public void setDistrictId(Short districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.region_id
     *
     * @return the value of ecs_virtual_goods_district.region_id
     *
     * @mbg.generated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.region_id
     *
     * @param regionId the value for ecs_virtual_goods_district.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.district_name
     *
     * @return the value of ecs_virtual_goods_district.district_name
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.district_name
     *
     * @param districtName the value for ecs_virtual_goods_district.district_name
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.province
     *
     * @return the value of ecs_virtual_goods_district.province
     *
     * @mbg.generated
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.province
     *
     * @param province the value for ecs_virtual_goods_district.province
     *
     * @mbg.generated
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.city
     *
     * @return the value of ecs_virtual_goods_district.city
     *
     * @mbg.generated
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.city
     *
     * @param city the value for ecs_virtual_goods_district.city
     *
     * @mbg.generated
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.county
     *
     * @return the value of ecs_virtual_goods_district.county
     *
     * @mbg.generated
     */
    public Short getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.county
     *
     * @param county the value for ecs_virtual_goods_district.county
     *
     * @mbg.generated
     */
    public void setCounty(Short county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.sort
     *
     * @return the value of ecs_virtual_goods_district.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.sort
     *
     * @param sort the value for ecs_virtual_goods_district.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_goods_district.is_show
     *
     * @return the value of ecs_virtual_goods_district.is_show
     *
     * @mbg.generated
     */
    public Short getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_goods_district.is_show
     *
     * @param isShow the value for ecs_virtual_goods_district.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Short isShow) {
        this.isShow = isShow;
    }
}