package org.lint.Entity;

public class EcsVirtualDistrict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_district.district_id
     *
     * @mbg.generated
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_district.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_virtual_district.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_district.district_id
     *
     * @return the value of ecs_virtual_district.district_id
     *
     * @mbg.generated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_district.district_id
     *
     * @param districtId the value for ecs_virtual_district.district_id
     *
     * @mbg.generated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_district.goods_id
     *
     * @return the value of ecs_virtual_district.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_district.goods_id
     *
     * @param goodsId the value for ecs_virtual_district.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_virtual_district.supplier_id
     *
     * @return the value of ecs_virtual_district.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_virtual_district.supplier_id
     *
     * @param supplierId the value for ecs_virtual_district.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
}