package org.lint.Entity;

public class EcsVoteOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vote_option.option_id
     *
     * @mbg.generated
     */
    private Short optionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vote_option.vote_id
     *
     * @mbg.generated
     */
    private Short voteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vote_option.option_name
     *
     * @mbg.generated
     */
    private String optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vote_option.option_count
     *
     * @mbg.generated
     */
    private Integer optionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vote_option.option_order
     *
     * @mbg.generated
     */
    private Byte optionOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vote_option.option_id
     *
     * @return the value of ecs_vote_option.option_id
     *
     * @mbg.generated
     */
    public Short getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vote_option.option_id
     *
     * @param optionId the value for ecs_vote_option.option_id
     *
     * @mbg.generated
     */
    public void setOptionId(Short optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vote_option.vote_id
     *
     * @return the value of ecs_vote_option.vote_id
     *
     * @mbg.generated
     */
    public Short getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vote_option.vote_id
     *
     * @param voteId the value for ecs_vote_option.vote_id
     *
     * @mbg.generated
     */
    public void setVoteId(Short voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vote_option.option_name
     *
     * @return the value of ecs_vote_option.option_name
     *
     * @mbg.generated
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vote_option.option_name
     *
     * @param optionName the value for ecs_vote_option.option_name
     *
     * @mbg.generated
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vote_option.option_count
     *
     * @return the value of ecs_vote_option.option_count
     *
     * @mbg.generated
     */
    public Integer getOptionCount() {
        return optionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vote_option.option_count
     *
     * @param optionCount the value for ecs_vote_option.option_count
     *
     * @mbg.generated
     */
    public void setOptionCount(Integer optionCount) {
        this.optionCount = optionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vote_option.option_order
     *
     * @return the value of ecs_vote_option.option_order
     *
     * @mbg.generated
     */
    public Byte getOptionOrder() {
        return optionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vote_option.option_order
     *
     * @param optionOrder the value for ecs_vote_option.option_order
     *
     * @mbg.generated
     */
    public void setOptionOrder(Byte optionOrder) {
        this.optionOrder = optionOrder;
    }
}