package org.lint.Entity;

public class EcsValidateRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.record_key
     *
     * @mbg.generated
     */
    private String recordKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.record_type
     *
     * @mbg.generated
     */
    private String recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.last_send_time
     *
     * @mbg.generated
     */
    private Integer lastSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.expired_time
     *
     * @mbg.generated
     */
    private Integer expiredTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.create_time
     *
     * @mbg.generated
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.record_code
     *
     * @mbg.generated
     */
    private String recordCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_validate_record.ext_info
     *
     * @mbg.generated
     */
    private String extInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.record_key
     *
     * @return the value of ecs_validate_record.record_key
     *
     * @mbg.generated
     */
    public String getRecordKey() {
        return recordKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.record_key
     *
     * @param recordKey the value for ecs_validate_record.record_key
     *
     * @mbg.generated
     */
    public void setRecordKey(String recordKey) {
        this.recordKey = recordKey == null ? null : recordKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.record_type
     *
     * @return the value of ecs_validate_record.record_type
     *
     * @mbg.generated
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.record_type
     *
     * @param recordType the value for ecs_validate_record.record_type
     *
     * @mbg.generated
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType == null ? null : recordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.last_send_time
     *
     * @return the value of ecs_validate_record.last_send_time
     *
     * @mbg.generated
     */
    public Integer getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.last_send_time
     *
     * @param lastSendTime the value for ecs_validate_record.last_send_time
     *
     * @mbg.generated
     */
    public void setLastSendTime(Integer lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.expired_time
     *
     * @return the value of ecs_validate_record.expired_time
     *
     * @mbg.generated
     */
    public Integer getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.expired_time
     *
     * @param expiredTime the value for ecs_validate_record.expired_time
     *
     * @mbg.generated
     */
    public void setExpiredTime(Integer expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.create_time
     *
     * @return the value of ecs_validate_record.create_time
     *
     * @mbg.generated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.create_time
     *
     * @param createTime the value for ecs_validate_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.record_code
     *
     * @return the value of ecs_validate_record.record_code
     *
     * @mbg.generated
     */
    public String getRecordCode() {
        return recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.record_code
     *
     * @param recordCode the value for ecs_validate_record.record_code
     *
     * @mbg.generated
     */
    public void setRecordCode(String recordCode) {
        this.recordCode = recordCode == null ? null : recordCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_validate_record.ext_info
     *
     * @return the value of ecs_validate_record.ext_info
     *
     * @mbg.generated
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_validate_record.ext_info
     *
     * @param extInfo the value for ecs_validate_record.ext_info
     *
     * @mbg.generated
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }
}