package org.lint.Entity;

import java.util.Date;

public class EcsWeixinJflog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.fake_id
     *
     * @mbg.generated
     */
    private String fakeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.jf_type
     *
     * @mbg.generated
     */
    private Integer jfType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.key_id
     *
     * @mbg.generated
     */
    private Integer keyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.createtime
     *
     * @mbg.generated
     */
    private Integer createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.createymd
     *
     * @mbg.generated
     */
    private Date createymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_jflog.num
     *
     * @mbg.generated
     */
    private Byte num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.id
     *
     * @return the value of ecs_weixin_jflog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.id
     *
     * @param id the value for ecs_weixin_jflog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.fake_id
     *
     * @return the value of ecs_weixin_jflog.fake_id
     *
     * @mbg.generated
     */
    public String getFakeId() {
        return fakeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.fake_id
     *
     * @param fakeId the value for ecs_weixin_jflog.fake_id
     *
     * @mbg.generated
     */
    public void setFakeId(String fakeId) {
        this.fakeId = fakeId == null ? null : fakeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.jf_type
     *
     * @return the value of ecs_weixin_jflog.jf_type
     *
     * @mbg.generated
     */
    public Integer getJfType() {
        return jfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.jf_type
     *
     * @param jfType the value for ecs_weixin_jflog.jf_type
     *
     * @mbg.generated
     */
    public void setJfType(Integer jfType) {
        this.jfType = jfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.key_id
     *
     * @return the value of ecs_weixin_jflog.key_id
     *
     * @mbg.generated
     */
    public Integer getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.key_id
     *
     * @param keyId the value for ecs_weixin_jflog.key_id
     *
     * @mbg.generated
     */
    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.createtime
     *
     * @return the value of ecs_weixin_jflog.createtime
     *
     * @mbg.generated
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.createtime
     *
     * @param createtime the value for ecs_weixin_jflog.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.createymd
     *
     * @return the value of ecs_weixin_jflog.createymd
     *
     * @mbg.generated
     */
    public Date getCreateymd() {
        return createymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.createymd
     *
     * @param createymd the value for ecs_weixin_jflog.createymd
     *
     * @mbg.generated
     */
    public void setCreateymd(Date createymd) {
        this.createymd = createymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_jflog.num
     *
     * @return the value of ecs_weixin_jflog.num
     *
     * @mbg.generated
     */
    public Byte getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_jflog.num
     *
     * @param num the value for ecs_weixin_jflog.num
     *
     * @mbg.generated
     */
    public void setNum(Byte num) {
        this.num = num;
    }
}