package org.lint.Entity;

import java.util.Date;

public class EcsWeixinSignconf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.startymd
     *
     * @mbg.generated
     */
    private Date startymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.endymd
     *
     * @mbg.generated
     */
    private Date endymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.bignum
     *
     * @mbg.generated
     */
    private Integer bignum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_signconf.addnum
     *
     * @mbg.generated
     */
    private Integer addnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.cid
     *
     * @return the value of ecs_weixin_signconf.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.cid
     *
     * @param cid the value for ecs_weixin_signconf.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.startymd
     *
     * @return the value of ecs_weixin_signconf.startymd
     *
     * @mbg.generated
     */
    public Date getStartymd() {
        return startymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.startymd
     *
     * @param startymd the value for ecs_weixin_signconf.startymd
     *
     * @mbg.generated
     */
    public void setStartymd(Date startymd) {
        this.startymd = startymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.endymd
     *
     * @return the value of ecs_weixin_signconf.endymd
     *
     * @mbg.generated
     */
    public Date getEndymd() {
        return endymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.endymd
     *
     * @param endymd the value for ecs_weixin_signconf.endymd
     *
     * @mbg.generated
     */
    public void setEndymd(Date endymd) {
        this.endymd = endymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.num
     *
     * @return the value of ecs_weixin_signconf.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.num
     *
     * @param num the value for ecs_weixin_signconf.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.bignum
     *
     * @return the value of ecs_weixin_signconf.bignum
     *
     * @mbg.generated
     */
    public Integer getBignum() {
        return bignum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.bignum
     *
     * @param bignum the value for ecs_weixin_signconf.bignum
     *
     * @mbg.generated
     */
    public void setBignum(Integer bignum) {
        this.bignum = bignum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_signconf.addnum
     *
     * @return the value of ecs_weixin_signconf.addnum
     *
     * @mbg.generated
     */
    public Integer getAddnum() {
        return addnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_signconf.addnum
     *
     * @param addnum the value for ecs_weixin_signconf.addnum
     *
     * @mbg.generated
     */
    public void setAddnum(Integer addnum) {
        this.addnum = addnum;
    }
}