package org.lint.Entity;

import java.util.Date;

public class EcsWeixinSign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_sign.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_sign.wxid
     *
     * @mbg.generated
     */
    private Integer wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_sign.signtime
     *
     * @mbg.generated
     */
    private Integer signtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_sign.signymd
     *
     * @mbg.generated
     */
    private Date signymd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_sign.sid
     *
     * @return the value of ecs_weixin_sign.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_sign.sid
     *
     * @param sid the value for ecs_weixin_sign.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_sign.wxid
     *
     * @return the value of ecs_weixin_sign.wxid
     *
     * @mbg.generated
     */
    public Integer getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_sign.wxid
     *
     * @param wxid the value for ecs_weixin_sign.wxid
     *
     * @mbg.generated
     */
    public void setWxid(Integer wxid) {
        this.wxid = wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_sign.signtime
     *
     * @return the value of ecs_weixin_sign.signtime
     *
     * @mbg.generated
     */
    public Integer getSigntime() {
        return signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_sign.signtime
     *
     * @param signtime the value for ecs_weixin_sign.signtime
     *
     * @mbg.generated
     */
    public void setSigntime(Integer signtime) {
        this.signtime = signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_sign.signymd
     *
     * @return the value of ecs_weixin_sign.signymd
     *
     * @mbg.generated
     */
    public Date getSignymd() {
        return signymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_sign.signymd
     *
     * @param signymd the value for ecs_weixin_sign.signymd
     *
     * @mbg.generated
     */
    public void setSignymd(Date signymd) {
        this.signymd = signymd;
    }
}