package org.lint.Entity;

public class EcsWeixinPaylog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_paylog.lid
     *
     * @mbg.generated
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_paylog.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_weixin_paylog.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_paylog.lid
     *
     * @return the value of ecs_weixin_paylog.lid
     *
     * @mbg.generated
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_paylog.lid
     *
     * @param lid the value for ecs_weixin_paylog.lid
     *
     * @mbg.generated
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_paylog.type
     *
     * @return the value of ecs_weixin_paylog.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_paylog.type
     *
     * @param type the value for ecs_weixin_paylog.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_weixin_paylog.log
     *
     * @return the value of ecs_weixin_paylog.log
     *
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_weixin_paylog.log
     *
     * @param log the value for ecs_weixin_paylog.log
     *
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }
}